### ISSUE TITLE
merge html > head

### ISSUE THREAD

**Issue by mira-kovar** [gmrchk/swup#1]
Hi,
it is possible to change html head tags? Lib change only title? What if I need to load another script or style on view change? Or need to change some meta description, og (opengraph) tags etc..

**Comment by gmrchk** [comment]
Hello there, 

Meta descriptions as well as og tags are read directly form the server. For example, if you share link on facebook, facebook will download the page and check the og tags right from the server, so the content of your head tag in your browser is irelevant here. 

For loading scripts or tags... That depends on your solution. If you're using some bundler to separate your code, you can set it up to load parts of your code/styles when it's needed.

If it's simply a code that you wrote for each page, I would suggest to load it all and then enable correct parts based on your DOM. For example, you could have a function run on `swup:pageView` event which would check a class of page (in case the code is based on page), or presence of some elements that are needed for code to run, and based on that run parts of the code. For styles - limit the style based on some page class and load it all together as well.

 If you would really like to replace the content of the head tag, you could do so on `swup:contentReplaced` event, where the whole content of loaded pages can be accessed in swups cache (including the head tag) and manually replaced by you.

**Comment by hrastnik** [comment]
@gmrchk I think you should reconsider replacing the `<head>` tag. Pages can have different stylesheets in `<head>` tags on different subpages.

I've actually implemented my own version of a "page transitioner" where I use the following method to replace the `<head>` tag. It's checks if tags from the next page already exist on the current page and doesn't replace them if they do. This is done to prevent CSS re-evaluation that happens when the style tag is replaced.

```
replaceHeadWithoutReplacingExistingTags = function(
    oldHead,
    newHead
  ) {
    var oldTags = oldHead.children;
    var newTags = newHead.children;
    var oldTagsToRemove = [];
    var newTagsToRemove = [];

    for (var i = 0; i < oldTags.length; i++) {
      var oldTag = oldTags[i];

      var oldTagIdentifier = oldTag.outerHTML;
      var foundInNewHead = false;
      for (var j = 0; j < newTags.length; j++) {
        var newTag = newTags[j];
        var newTagIdentifier = newTag.outerHTML;

        if (newTagIdentifier === oldTagIdentifier) {
          foundInNewHead = true;
          break;
        }
      }

      if (foundInNewHead) newTagsToRemove.push(newTag);
      else oldTagsToRemove.push(oldTag);
    }

    for (var i = 0; i < newTagsToRemove.length; i++) {
      newHead.removeChild(newTagsToRemove[i]);
    }

    for (var i = 0; i < oldTagsToRemove.length; i++) {
      oldHead.removeChild(oldTagsToRemove[i]);
    }

    var fragment = document.createDocumentFragment();
    for (var i = 0; i < newHead.children.length; i++) {
      fragment.appendChild(newHead.children[i]);
    }
    oldHead.appendChild(fragment);
  };
```

**Comment by gmrchk** [comment]
I've never used such approach, but I see why someone would. I will create a plugin-like solution for this that you could use some time during this week.

**Comment by gmrchk** [comment]
Here is a plugin that should solve this issues [swupmergeheadplugin](https://github.com/gmrchk/swup#swupmergeheadplugin). 

I'm not really using this approach in my projects so... let me know if there is some trouble.
