### ISSUE TITLE
swup with vue.js

### ISSUE THREAD

**Issue by paallaire** [gmrchk/swup#10]
Do you have any tips on how to implement swup with vue.js ?

vue.js
https://vuejs.org/

Great work !

**Comment by phiwut** [comment]
Vue already provides a transition wrapper component. You can see it in the docs here: https://vuejs.org/v2/guide/transitions.html

**Comment by gmrchk** [comment]
As @phiwut mentioned, Vue.js already provides this functionality very well. If you would like to get some head start with using Vue.js for page transitions, [this](https://css-tricks.com/native-like-animations-for-page-transitions-on-the-web/) could help.

Closing the issue.

**Comment by stuartcusackie** [comment]
or you might just try something like this:

```
swup.on('contentReplaced', init);
function init () {
	const app = new Vue({
	    el: '#app',
	});
}
```
