### ISSUE TITLE
Option to exclude shift-click and cmd-click from triggering transitions

### ISSUE THREAD

**Issue by usame-algan** [gmrchk/swup#102]
Is there a way to exclude shift-click and cmd-click from triggering swup transitions? For when a user wants to open a link in a new page/tab.

**Comment by 23d1** [comment]
It works as expected for me. Sounds odd that it wouldn't work, as it's simply a browser feature that is called before anything else, right?

**Comment by usame-algan** [comment]
Changing the following line in the [index.js](https://github.com/gmrchk/swup/blob/master/src/index.js) fixed it for me

`if (!event.metaKey)`

to

`if (!event.ctrlKey && !event.shiftKey)`

**Comment by gmrchk** [comment]
Hi,

`shift-click` is not implemented in swup right now... will fix that. 
`cmd-click` seems to work as expected anywhere I test it. Is it something you have found not working properly as well? If so, can you please share where?

Thanks for reporting!

**Comment by usame-algan** [comment]
After testing it again cmd-click on Mac works as expected. The problem seems to be with Windows Keyboards and ctrl-click which should have the same functionality as cmd-click.
`event.metaKey` seems to be false in those cases.
See: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey

**Comment by gmrchk** [comment]
Swup now detects press of shift/ctrl/cmd/alt keys, prevents from running the transition and doesn't rewrite the native behavior of the browser when one of the keys is pressed.

@usame-algan thank you for digging into it.
