### ISSUE TITLE
swup freezes all other javascript on the page

### ISSUE THREAD

**Issue by derridHeidegger** [gmrchk/swup#108]
hi
i am working on a wordpress theme and want to include swup as a page transition. thing is if i do not pass options the effect doesn't happen. once i do pass options, the effect works but once the transition is over, all other javascript on the page doesn't work, without the console errors, just doesn't work.
so this is my code:
```javascript
let swupoptions = {
  LINK_SELECTOR: 'a[href^="' + window.location.origin + '"]:not([data-no-swup]), a[href^="/"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup])',
  FORM_SELECTOR: 'form[data-swup-form]',
  elements: [
      '#page' //my content wrapper div
  ],
  animationSelector: '[class*="swup-transition-"]',
  cache: true,
  pageClassPrefix: '',
  scroll: false,
  debugMode: false,
  preload: true,
  support: true,
  skipPopStateHandling: function(event){
      if (event.state && event.state.source == "page") {
          return false;
      }
      return true;
  },
  animateHistoryBrowsing: false,
}
const swup = new Swup(swupoptions);
```

what am i missing here?

best regards

**Comment by derridHeidegger** [comment]
anyone?

**Comment by alcantara** [comment]
check the readme under events. 

`
swup.on('contentReplaced', function() {
     // scripts you want replaced.
});
`

**Comment by derridHeidegger** [comment]
thanks for the answer, but how exactly can i reload jequery in that sense, especially when i view source code, jquery is there.

**Comment by alcantara** [comment]
You don't need to reload jquery. Just the functions that stop working.

**Comment by gmrchk** [comment]
Hi, sorry for the delay.

as @alcantara mentioned, you don't need to reload jQuery and stuff. It is already loaded and defined in the global `$` variable. However, when you run a script like the one below,

```javascript
$(element).on('click', ...);
```

it works with a particular element/s on the page. When the page content gets replaced by swup, old elements with listeners are not there anymore, and new ones are present on the page without those listeners. You need to re-run such code on the `contentReplaced` event. 

[This thread](https://github.com/gmrchk/swup/issues/41) might help you get started.
