### ISSUE TITLE
Is there a way to track page index?

### ISSUE THREAD

**Issue by alcantara** [gmrchk/swup#109]
Each time swup makes a transition it counts as a new page. Is there a way to have the same functionality as a regular website?

Can I keep track of where the user is through an index?

**Comment by gmrchk** [comment]
Swup preserves the browser history functionality, so when the user goes back/forward, it will work the same way as browser normally does. 

If you'd like to track users and their navigation through your site, I would suggest using Google Analytics together with [GA plugin](https://github.com/gmrchk/swup#swupgaplugin) or [GTM plugin](https://github.com/gmrchk/swup#swupgtmplugin). GA offers lots of information you could find useful.

If you like to save your data elsewhere and track users manually, you can use swup [events](https://github.com/gmrchk/swup#events) to read `window.location.href` or any other information accessible in the browser at the right moment and further use it (run some code based on page / save current location to DB, etc.).

Do you have some particular use case?
