### ISSUE TITLE
Table row data attribute

### ISSUE THREAD

**Issue by AugmentBLU** [gmrchk/swup#110]
Hello, is it possible to use use a data attribute that has a URL instead of only using href links so that I can allow table rows to be clickable? Rather than have individual links within a row, I wanted to have the entire row clickable and the URL be take from a data attribute. 

Like

```
<td data-href="https://my-site.gg/update/efaf6ba0" class="list-cell">
An Item
</td>
```

Thanks

**Comment by gmrchk** [comment]
Hi,

you can use [swup API](https://github.com/gmrchk/swup#api) to transition to another page. The `loadPage` method to be precise.

You could use something as the following:
```javascript
var swup = new Swup(options);

document.querySelectorAll('[data-href]').forEach(function (element) {
    element.addEventListener('click', function(event) {
        swup.loadPage({ url: event.target.dataset.href });
    });
});
```
