### ISSUE TITLE
Smooth Scroll offset

### ISSUE THREAD

**Issue by MikeHarrison** [gmrchk/swup#113]
Hi,

As before, hats off for an awesome bit of work. One small request - would it be possible to add an option for a pixel offset on the smooth scrolling? To allow for a fixed header for instance - at the moment the top of my content section is disappearing behind my sticky nav. Something like:

`scrollOffset: 200`

I understand this is a page transition library not a smooth scroll one so totally understand if this is a complexity you don't want to add!

Thanks again

**Comment by gmrchk** [comment]
Hi, nice question!

I believe anchors should lead to the correct spot on your page, even when no JS handling is present (like when you're coming from another page with a link leading to the exact place on the page with the `#anchor`). I guess there is nothing wrong with adding an offset with JS tho and it might just be my "weird thing".

One handy trick I've learned over the years is using a separate element inside of the section as an anchor. As it's a separate element, it can be positioned relative to its parent, and so, compensate for the fixed header.

```html
<section>
    <div id="need-to-scroll-here" class="anchor"></div>
    ...
</section>
```

```css
.anchor {
    position: relative;
    top: -100px; // your offset
}
```

The good thing about this approach is that it will lead to the correct place even without JS and you can change the offset with a simple CSS media query.

Not so good thing is that some IE versions will ignore a link leading to that anchor if its parent has `overflow: hidden`... I usually fix that with something like:

```javascript
// run only for IE
queryAll('[href^="#"]').forEach(link => {
    link.addEventListener('click', event => {
        document.documentElement.scrollTop = Math.round(document.querySelector(event.target.hash).getBoundingClientRect().top) + window.pageYOffset;
    });
});
```

If that's not something you would like to do, there is always an option to disable swups scroll control and use it's `scrollTo` method and swup events to scroll when you want, where you want... or rewrite the `scrollTo` method altogether to include your offset. 

To wrap it up, I don't think another option is necessary, as there are other ways to achieve this, but I will add this topic to the [Common Issues](https://github.com/gmrchk/swup/wiki/Common-issues), as I'm pretty sure you're not the first one to ask such question.

**Comment by MikeHarrison** [comment]
Thanks for the detailed reply, much appreciated.

I like the look of the absolutely positioned element with the offset, I think that solution will work fine for me. It also allows the offset to be changed with media queries to adjust for a different height fixed header at different screen sizes if needed.

I will take a look at the IE compatibility, though the vast majority of sites I work on only require IE11 so hopefully shouldn't be too complicated.

Thanks again!
