### ISSUE TITLE
Wordpress integration - plugins with JS

### ISSUE THREAD

**Issue by ryandc** [gmrchk/swup#116]
Apologies if this has been brought up in another thread, but I couldn't see the same sort of usage (or at least a solution).

Guessing this is a fairly common issue to encounter, but I've got my WP site working with Swup, where all my JS inits again on contentReplaced, but any wordpress plugins don't work after navigating away from the initial page you hit the site on.

Is getting this to work going to be dependant on each plugin having some sort of accessible event I can re-init, or is is there anything Sup offers?

Thanks in advance

**Comment by gmrchk** [comment]
Hi @ryandc , sorry for the delay.

I believe any plugin should have some kind of method that initializes it, and it's only a matter of debugging the code injected by the plugins to see what it is. 

Checking the plugin documentation or contacting the plugin support should be the quickest way to get to the bottom of it.

In the worst case, there is always an option to rerun a whole loaded JS file/JS inline script, like the [merge head plugin](https://github.com/gmrchk/swup/blob/master/src/plugins/swupMergeHeadPlugin.js) does.

**Comment by gmrchk** [comment]
#117 seems to be a related issue and solution kind of confirms what I was saying.

**Comment by ryandc** [comment]
Thanks @gmrchk, appreciate the response and that it's beyond the remit of the plugin.

I took your advice and delved into the plugin and found a function I could init :)

**Comment by gmrchk** [comment]
@ryandc Glad I could help. If you could post the code/solution you used for future reference, it would be awesome!

**Comment by zkingdesign** [comment]
@ryandc could you share your solution? Having the exact same issues as you do.
