### ISSUE TITLE
Doubt with is-changing

### ISSUE THREAD

**Issue by fuzzrs** [gmrchk/swup#119]
Hi, how can i supposed to use is-changing? i want to display a loader while the page content are loading, and then starts with the transitions, but i get stuck with the loading screen

.transition-loader {
	visibility: hidden;
	opacity: 0;
	transition: .4s;
}

html.is-changing .transition-loader {
	visibility: visible;
	opacity: 1;
}

is that wrong?

**Comment by MartDSam** [comment]
Hello @fuzzrs put your SWUP configuration here for us to see.

**Comment by alcantara** [comment]
Try changing `.transition-loader` to `.loader`. You only have to setup `.transition-` once as in `.transition-fade`. 

Check [Common Issues](https://github.com/gmrchk/swup/wiki/Common-Issues).

**Comment by fuzzrs** [comment]
now i'm using is-animating on loader div for the effect, but you can give me a simple example of is-changing?

**Comment by alcantara** [comment]
#38 #90

**Comment by alcantara** [comment]
#38

**Comment by fuzzrs** [comment]
thanks @alcantara!
