### ISSUE TITLE
Create GA/GTM plugin

### ISSUE THREAD

**Issue by gmrchk** [gmrchk/swup#12]
Plugins for Google Analytics and Google Tag Manager.

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by phiwut** [comment]
Maybe you should take a similar approach to Turbolink. It merges the contents of the <head> element.

In detail:
"Turbolinks looks for any <script> elements in the new page’s <head> which aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and evaluated by the browser."

https://github.com/turbolinks/turbolinks#working-with-script-elements

**Comment by gmrchk** [comment]
Of course, it's an option to run inline scripts on the page which would trigger the analytics, but I would like it to be more of a plug&play solution without any additional setup. This is possible and I have it ready, just didn't have time to test it yet. 

When it comes to using your scripts the "Turbolinks way", I have mentioned it before that I don't see it as a correct approach for a website with no actual page reloads, and that's why it's not part of swup. However, [swupMergeHeadPlugin](https://github.com/gmrchk/swup#swupmergeheadplugin) can run  scripts inside of the head tag. Feel free to create a plugin that would run the scripts encountered in the replaced blocks. swupMergeHeadPlugin should serve as a good base for that.

**Comment by gmrchk** [comment]
I've posted a new [swupGaPlugin](https://github.com/gmrchk/swup#swupgaplugin) and [swupGtmPlugin](https://github.com/gmrchk/swup#swupgtmplugin) which should help when dealing with GA/GTM.

**GA plugin** does pretty much what you (@lmartins) have suggested. My only modification is to change it to not trigger the pageview on load because as I'm mentioning in docs, the `pageview` is triggered in [JavaScript tracking snippet](https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet) and in the worst case, can be triggered manually.

I would like to mention that including GA using `<script async src="https://www.googletagmanager.com/gtag/js?id=..."></script>` causes GA to not trigger pageview on standard `ga('send', 'pageview')` for some reason, but [this workaround](https://stackoverflow.com/questions/15744042/events-not-being-tracked-in-new-google-analytics-analytics-js-setup#answer-40761709) does the trick. This method of including GA is offered to me by default in analytics panel.

**GTM plugin** triggers event which can be used in GTM to do all that analytics stuff within GTM. This is a preferred method of "my analytics buddy", but I'm posting it here as others (more skilled with GTM then me) might prefer this method as well.

Your issue with **swupMergeHeadPlugin** was caused by emptying the cache too soon (when the cache is disabled) and is [fixed now](https://github.com/gmrchk/swup/commit/e2003861aac1a17355b38976f5304f3cfb6f9783), sorry about that. However, note that swupMergeHeadPlugin will place tags and run scripts only if it is not yet present in the head tag, so your GA triggering would have to be different for each page, although even JS comment with URL of the page would be enough.
