### ISSUE TITLE
swup loadpage in ie11

### ISSUE THREAD

**Issue by ynamite** [gmrchk/swup#121]
Is swup supposed to work with IE11?

At least in my app, swup doesn't seem to work in IE11. I get a warning that Promises aren't supported (not using any polyfills) and a bunch of xhtmlrequest errors. Any idea what could be the issue here? Everything works great in the latest Firefox, Chrome, Safari and Edge.

If you need any more information let me know.

**Comment by gmrchk** [comment]
Hi @ynamite,

As you can see [here](https://caniuse.com/#feat=promises), Promises are not supported by IE11 or lower. Promises are essential for swup, so if you want your transitions to be animated in IE11 as well, try adding a polyfill. 

However, from my experience, IEs are usually not that good in handling animations, so I usually just choose to disable swup on IE browsers altogether.
 
Though, no xhtmlrequest errors should be present in that case. Could you post a screenshot of those?

**Comment by ynamite** [comment]
Weird, I wanted to take screenshots just now but now the xhtmlrequest errors are gone. Maybe IE11 was acting weird. Not sure.

I'm not really using swup to animate anything in this case. It might be a little overkill to use swup for this, but I'm basically just using it to load and replace content :) 

I've tried a bunch of different promise polyfills, but none of them seem to jive with swup. Any recommendations for a polyfill that definitely works with swup?

**Comment by s3ththompson** [comment]
Looks like the issue is that swup is checking explicitly that Promises are natively supported: https://github.com/gmrchk/swup/blob/master/src/index.js#L166

**Comment by gmrchk** [comment]
Hi!

You're correct @s3ththompson, swup checks for native Pollifyl support. I guess back at the time I thought it would be better to check for native support (it's a check for browser support after all, and Polyfills could act not according to the specification).
In today's world, I'm quite sure we can remove this strict check, or maybe even consider removing support check altogether. I will see what's the support for different features these days and see based on that.

You have two options on how to approach this right now:
1. To any of your polyfill that you're using, add a method called `toString` that would return `[native code]`.

```javascript
Promise.toString = function() {
    return "[native code]";
}
```

2. Disable support check all together by setting `support` option to `false`.
