### ISSUE TITLE
es5 example?

### ISSUE THREAD

**Issue by aolko** [gmrchk/swup#122]
Do you have an example in good ol' es5 (es2009) without all those fancy classes and requires?

**Comment by ynamite** [comment]
Just include the transpiled and minified library from the dist folder and write ```var swup = new Swup();``` you're good to go.

**Comment by aolko** [comment]
Can i set `#swup` to `.swup`?
```
swup.options = {
    elements: ['.swup']
}
```

doesn't seem to be working, also i get
`Uncaught TypeError: Cannot set property 'url' of null`

**Comment by ynamite** [comment]
@aolko 
Check out the test site here https://massif.ch/swupthereitis/

Note: with the default LINK_SELECTOR you have to make sure you either have an absolute url in your links or a url that starts with a forward slash.

**Comment by gmrchk** [comment]
@aolko you can use any valid selector for swup containers (elements option), including `.swup`, but you need to set the options when creating the instance, as @ynamite's example suggests.

```javascript
var swup = new Swup({
    elements: ['.swup']
}); 
```
