### ISSUE TITLE
What is the correct usage of to-[content of data-swup-transition attribute]?

### ISSUE THREAD

**Issue by leecolarelli** [gmrchk/swup#123]
Hi, I am currently implementing swup and happy so far, except that i cannot get `to-[content of data-swup-transition attribute]` to work...

I have a fade transition on every page of the site, which is all working well. However, I also want a 'grow' transition on one icon/image on the homepage. I only want this transition to animate when the link containing the icon is clicked.

So I have added data-swup-transition="calendarlink" to the link, and `html.to-calendarlink .transition-grow {transform: scale(5);}` to my css. It works as desired, only animating when that link is clicked. 

However, as soon as it is added, no other pages will animate in. They are all broken. As soon as i remove this again, all works well again.

Could you please help with this? I have worked out that it works again if i also add an `html.is-animating .transition-grow` class, but this seems to prevent the `html.to-calendarlink .transition-grow` from working.

**Comment by gmrchk** [comment]
Hi,

That means that the animation **in** for the `.transition-grow` element never finishes. Please, try adding a default scale for this element.

```css
.transition-grow {
    transform: scale(1);
}
```

**Comment by leecolarelli** [comment]
Thanks for the reply. However, I already have that code. Anything else?

**Comment by gmrchk** [comment]
Hi @leecolarelli, sorry for the late reply. I'm not sure if you solved your issue, so I will try another option.

I think I misunderstood your problem. I think your problem is the usage of the `transition-*` for this. `transition-*` classes are used in swup for detecting the timing, which you don't really need if you just want the icon to grow, throughout other animations. Changing the class used on the icon will fix the issues causing swup to "get stuck".

**Comment by Zaperela** [comment]
@leecolarelli I had a similar issue with using `to-[content of data-swup-transition attribute]` to grow and shrink an element between pages. @gmrchk second option worked for me.

My CSS went from `html.to-sub-page .transition-grow {...}` to `html.to-sub-page .grow {...}` and now everything is working buttery smooth.

**Comment by luiscabre** [comment]
Hello everyone ..... I'm using Swup ..and it working fine so far ...I have 4 pages ( home, about, work, contact ) .....I made a fade transition  and it works fine ...but now I'd like to add different ( colors or backgound image ) on each page. .  I'm trying putting some backgound colours,   but it doesn't work  ....Please I need help with this.  
 
![swup-background-color](https://user-images.githubusercontent.com/17053257/110149668-b3428b00-7db4-11eb-94b7-54b0fa75d2de.png)






`
