### ISSUE TITLE
transition for hidden

### ISSUE THREAD

**Issue by ilyha81** [gmrchk/swup#125]
hidden elements seems not to be animating with "transition-" class. So animation never ends and page transition stops.

adding in css dont help:
*[hidden="hidden"] .transition- {
transition: none;} 

so if y have some switcher with hidden attr - y need to remove class "transition-" each time y add hidden to elem.

Is it possible to add swupOption to dont check "transition-" of hidden elements?

**Comment by gmrchk** [comment]
Hi, sorry for the late reply.

I'm assuming that some other library/plugin you are using is utilizing the `.transition-*` class, correct? If so, you can use the [animationSelector option](https://github.com/gmrchk/swup#animation-selector) to change the selector used by swup, to make it more strict, like `.swup-transition-`. You need to reflect that in your CSS as well. 

If you simply want to hide some elements that are in the normal case also supposed to animate during the transition, then that just won't work. You might consider using other class with the same CSS transition defined for those elements, so the animation will act the same, but swup won't consider it as an animation it should wait for. Also, you might want to read [this](https://github.com/gmrchk/swup#animation-selector).
