### ISSUE TITLE
TypeForm

### ISSUE THREAD

**Issue by thagxt** [gmrchk/swup#126]
I'm having problems loading the TypeForm script with SWUP after I've clicked the link to the page where TypeForm is loading and it doesn't load... if page refreshes it does loads.

What I've done was to put the TypeForm script inside a function and load it like this:

```
function contactForm() { 
(function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })();
}

contactForm();
document.addEventListener('swup:contentReplaced', contactForm);
```

any ideas on how to make it work? thank you

**Comment by gmrchk** [comment]
Hi @thagxt,

I see what you tried to do there, but this script most likely serves to load the TypeForm API, which automatically loads the form as well once API is loaded, and calling the same script won't have any good effect. To reload the form in some way, there must be some kind of function provided by TypeForm. 

In any way, this question should be direct to TypeForm guys. Ask something like "**How to make TypeForm work with Single Page Applications**".
