### ISSUE TITLE
Swup stuck on 'is-changing'

### ISSUE THREAD

**Issue by hechtron** [gmrchk/swup#13]
I'm getting the following error after including swup in my project. Any idea what's going on?

`swup.min.js:1 Uncaught (in promise) DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty`

Thanks much!

**Comment by gmrchk** [comment]
Can you please include a non-minified version of swup and post the error again?

**Comment by hechtron** [comment]
Sorry... i missed your response. 

Actually, I'm getting exactly the same error with the minified or non-minified versions.

**Comment by gmrchk** [comment]
I wanted to know on which line of code the error appeared in non-minified version, where I'm quite sure it is not on line 1... Should have made that clear, sorry about that. 
But anyway, I was digging around and I think I found the issue. 

In case that body element had an attribute which included " " at the beginning, end, or several in a row, swup would try to add the class "" in body `classList`, which leads to the mentioned error. 

The latest version (0.3.7) fixed the issue. Please update your version. If the problem persists after the update, please post the line where the error happens and reopen the issue. Thanks!

**Comment by SergeyFrancev** [comment]
I fix error message, after replace
`[class]="role === user.role ?'active':''"`
on
`[class.active]="role === user.role"`
