### ISSUE TITLE
swup stops at animationOutDone

### ISSUE THREAD

**Issue by patrickroppel** [gmrchk/swup#131]
i am very new to js. actually not much of an clue on what i do. but managed to install swup, animation out works very nicely but nothing further happens. initial page stays active, i see hoverLink when i move around. in the debug console window.  any ideas on what that could be?

i also get an error. which could be related to me running the page locally. i switched now to a mamp server but no change?

any help would be most appreciated.
![Uploading Screen Shot 2019-04-10 at 12.03.39.jpg…]()

**Comment by gmrchk** [comment]
Hi, unfortunately, I can't see the screenshot you have posted.

If the animation starts but gets stuck on "leave" state, it probably means that you have some element with `transition-*` class that doesn't have the transition CSS defined for it.

**Comment by gmrchk** [comment]
Closing as inactive. [Common issues](https://github.com/gmrchk/swup/wiki/Common-issues) might help tho.
