### ISSUE TITLE
Make swup working in wordpress site with Divi theme installed (or builder style themes)

### ISSUE THREAD

**Issue by f-naranjo** [gmrchk/swup#132]
Hi! First of all thanks for the great development made here :)

I am trying to use swup in my worpdress site but im using Divi theme, that has a builder, and i dont found the way to make swup run properly handling the divi's js files...

I have tried to apply the solution given in #41 but it doesn't work for me... i don`t know what i am doing wrong, i think that the approach would be the same (Run swup once the DOM is fully loaded).

I'm testing to insert it in my sandbox server somospiratas.com, some help would be much much apreciated!

**Comment by gmrchk** [comment]
Hi, if you have your site running somewhere and only JS after swup page load is the problem, it would be really helpful to see it. I can try to figure it out if you provide a demo or at least a code example.

In any way, if you know that rerunning the DIVI's scripts is the problem, it would probably be the best to point your question to the DIVI guys, as they will most likely know what you have to do.

**Comment by f-naranjo** [comment]
Hi gmrchk! Thank you for your answer!

I have finally made a template from scratch and swup works like a charm.

Anyway, i think it would be interesting to find a solution to the issue between builders and swup( i think it is a general problem with the wordpress builders like divi, unyson, etc. ). I have asked to DIVI guys but they couldn't figure out the solution. So I will install divi in my server and try again to make it work properly.

I think that the 'swup:contentReplaced' is the key to solve the issue. So i will write here if i achieve the solution or give you the access to see whats happening :)

Thank you again!

**Comment by gmrchk** [comment]
I think the main problem is that the site builders are usually not ready for this kind of integration, with scripts being used in many different ways, without providing some unified API for such scripts that are used in a template. Even if you want to manually replace a part of your page at some point (without using a full SPA emulation solution like swup), you might need to re-run the scripts, so there should be a way to do that provided by the template. 

You might get some more helpful info from DIVI later on, maybe they just didn't understand the question properly this time and weren't interested in helping one guy using some plugin from a web. 

If you figure this out, please, definitely get back to me. I'm all up for creating new official swup plugins and some site builders might be more "prepared" for this than others. The credit would be, of course, all yours.

Thanks for reporting! Closing.

**Comment by shawnstom** [comment]
@f-naranjo I am trying to use Swup with the Divi theme as well. I can get pages to fadeout, but the transition time between pages takes forever and the new page does not animate in. It seems that divi is still reloading the ENTIRE page. 

What was your end solution?

**Comment by f-naranjo** [comment]
Hi! I finally decided to create a Theme based on underscore and swup works
perfectly. For now i haven't had the solution to make swup works with
Divi...

**Comment by gmrchk** [comment]
Hi @shawnstom, maybe [this](https://swup.js.org/common-issues#missing-style-for-transition--class) will help? 

Also, I think this problem should be detected by a debug plugin, so I have created an [issue](https://github.com/swup/debug-plugin/issues/1) for that and will add detection into a debug plugin.

**Comment by Chisio91** [comment]
Hi @f-naranjo I’m creating a WordPress theme based on underscore. I integrated swup and it works but not correctly. The problem affects menu classes. Can u help me?

**Comment by f-naranjo** [comment]
Hi @liuk91 ! Im pleased to help you, but it's been a while since i did it and i don't remember well so please let me know more in detail your problem and i will try to help :)

**Comment by liuk91** [comment]
In my bootstrap navbar I set a condition

<?php if (is_page_template('homepage.php')): ?>
	<div class="navbar-brand" href="#"><h1 class="name">Site Name</h1></div>
<?php else: ?>
	<a class="navbar-brand" href="<?php echo esc_url(home_url('/')); ?>"><div class="name">Site Name</div></a>
<?php endif; ?>

But with swup it doesn't work... it is as if it remained in the same page template.
I set correctly SwupScrollPlugin, SwupBodyClassPlugin...

**Comment by f-naranjo** [comment]
Sorry but i don't understand well because i dont know php, but what you're trying to do it's to set the href based on the `home_url` parameter, like `#home` ,  `#about` ? I think that maybe you need to load the plugin on `window.onload` to be sure that this field is ok...

**Comment by liuk91** [comment]
Sorry, I forgot to insert code with the button and the github preview didn't show it... now I edited the previous message.
