### ISSUE TITLE
Url and replace content

### ISSUE THREAD

**Issue by natdev** [gmrchk/swup#134]
Hi, i am using wordpress and i use this plugin for the first time. My issue is the following : when click on a link the start of the animation work but don't replace the content and the url doesn't change neither. 

I have this message in my console:
Uncaught TypeError: Cannot read property 'innerText' of null
    at Swup.module.exports [as getDataFromHtml] (getDataFromHtml.js:26)
    at Swup.enable (index.js:282)
    at new Swup (index.js:225)
    at eval (index.js:66)
    at Module../js/index.js (bundle.js?ver=1.0:152)
    at __webpack_require__ (bundle.js?ver=1.0:20)
    at bundle.js?ver=1.0:84
    at bundle.js?ver=1.0:87
Thank u for your help

**Comment by gmrchk** [comment]
Hi, I'm working on improving the error reporting so this kind of errors that don't tell you anything don't happen in the future.

In a meanwhile, can you provide a code example of swup settings, or even better, live demo of the site? Kind of looks like you're missing `#swup` element in your HTML (which is a default value of [elements option](https://github.com/gmrchk/swup#elements)), but that's just a wild guess.

**Comment by natdev** [comment]
Hi @gmrchk I include this header below on every page : 
<div class="slim-header">
    <div class="container">
        <div class="slim-header-left">
            <h2 class="slim-logo"><a href="index.html">slim<span>.</span></a></h2>

            <div class="search-box">
                <input type="text" class="form-control" placeholder="Search">
                <button class="btn btn-primary"><i class="fa fa-search"></i></button>
            </div>
        </div>
        <div class="slim-header-right">
            <div class="dropdown dropdown-a">
                <a href="" class="header-notification" data-toggle="dropdown">
                    <i class="icon ion-ios-bolt-outline"></i>
                </a>
                <div class="dropdown-menu">
                    <div class="dropdown-menu-header">
                        <h6 class="dropdown-menu-title">Activity Logs</h6>
                        <div>
                            <a href="">Filter List</a>
                            <a href="">Settings</a>
                        </div>
                    </div>
                    <div class="dropdown-activity-list">
                        <div class="activity-label">Today, December 13, 2017</div>
                        <div class="activity-item">
                            <div class="row no-gutters">
                                <div class="col-2 tx-right">10:15am</div>
                                <div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
                                <div class="col-8">Purchased christmas sale cloud storage</div>
                            </div>
                        </div>
                        <div class="activity-item">
                            <div class="row no-gutters">
                                <div class="col-2 tx-right">9:48am</div>
                                <div class="col-2 tx-center"><span class="square-10 bg-danger"></span></div>
                                <div class="col-8">Login failure</div>
                            </div>
                        </div>
                        <div class="activity-item">
                            <div class="row no-gutters">
                                <div class="col-2 tx-right">7:29am</div>
                                <div class="col-2 tx-center"><span class="square-10 bg-warning"></span></div>
                                <div class="col-8">(D:) Storage almost full</div>
                            </div>
                        </div>
                        <div class="activity-item">
                            <div class="row no-gutters">
                                <div class="col-2 tx-right">3:21am</div>
                                <div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
                                <div class="col-8">1 item sold <strong>Christmas bundle</strong></div>
                            </div>
                        </div>
                        <div class="activity-label">Yesterday, December 12, 2017</div>
                        <div class="activity-item">
                            <div class="row no-gutters">
                                <div class="col-2 tx-right">6:57am</div>
                                <div class="col-2 tx-center"><span class="square-10 bg-success"></span></div>
                                <div class="col-8">Earn new badge <strong>Elite Author</strong></div>
                            </div>
                        </div>
                    </div>
                    <div class="dropdown-list-footer">
                        <a href="page-activity.html"><i class="fa fa-angle-down"></i> Show All Activities</a>
                    </div>
                </div>
            </div>
            <div class="dropdown dropdown-b">
                <a href="" class="header-notification" data-toggle="dropdown">
                    <i class="icon ion-ios-bell-outline"></i>
                    <span class="indicator"></span>
                </a>
                <div class="dropdown-menu">
                    <div class="dropdown-menu-header">
                        <h6 class="dropdown-menu-title">Notifications</h6>
                        <div>
                            <a href="">Mark All as Read</a>
                            <a href="">Settings</a>
                        </div>
                    </div>
                    <div class="dropdown-list">
                        
                        <a href="" class="dropdown-link">
                            <div class="media">
                                <img src="http://via.placeholder.com/500x500" alt="">
                                <div class="media-body">
                                    <p><strong>Suzzeth Bungaos</strong> tagged you and 18 others in a post.</p>
                                    <span>October 03, 2017 8:45am</span>
                                </div>
                            </div>
                        </a>
                        
                        <a href="" class="dropdown-link">
                            <div class="media">
                                <img src="http://via.placeholder.com/500x500" alt="">
                                <div class="media-body">
                                    <p><strong>Mellisa Brown</strong> appreciated your work <strong>The Social Network</strong></p>
                                    <span>October 02, 2017 12:44am</span>
                                </div>
                            </div>
                        </a>
                        <a href="" class="dropdown-link read">
                            <div class="media">
                                <img src="http://via.placeholder.com/500x500" alt="">
                                <div class="media-body">
                                    <p>20+ new items added are for sale in your <strong>Sale Group</strong></p>
                                    <span>October 01, 2017 10:20pm</span>
                                </div>
                            </div>
                        </a>
                        <a href="" class="dropdown-link read">
                            <div class="media">
                                <img src="http://via.placeholder.com/500x500" alt="">
                                <div class="media-body">
                                    <p><strong>Julius Erving</strong> wants to connect with you on your conversation with <strong>Ronnie Mara</strong></p>
                                    <span>October 01, 2017 6:08pm</span>
                                </div>
                            </div>
                        </a>
                        <div class="dropdown-list-footer">
                            <a href="page-notifications.html"><i class="fa fa-angle-down"></i> Show All Notifications</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="dropdown dropdown-c">
                <a href="#" class="logged-user" data-toggle="dropdown">
                    <img src="http://via.placeholder.com/500x500" alt="">
                    <span><?php echo  ucfirst(get_user_meta(get_current_user_id(),'first_name',true));?></span>
                    <i class="fa fa-angle-down"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right">
                    <nav class="nav">
                        <a href="<?php echo site_url('profile');?>" class="nav-link"><i class="icon ion-person"></i> View Profile</a>
                        <a href="<?php echo site_url('edit-profile');?>" class="nav-link"><i class="icon ion-compose"></i> Edit Profile </a>
                        <a href="<?php echo wp_logout_url(); ?>" class="nav-link"><i class="icon ion-forward"></i> Sign Out</a>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="slim-navbar" class="slim-navbar">
        <div class="container">
            <?php wp_nav_menu(array(
                    'menu'              => 'primary',
                    'container'         => false,
                    'menu_class'        => 'nav',
                    'walker'            => new com_walker()
                ));?>
        </div>
</div>
<main id="swup" class="slim-mainpanel transition-fade">
    <div  class="container">


        <div class="slim-pageheader">
            <ol class="breadcrumb slim-breadcrumb">
                <li class="breadcrumb-item <?php echo (is_home())?"active":""; ?>"> <?php echo (!is_front_page())? "<a href=\"".home_url()."\">Dashboard</a>" : "Dashboard"; ?></li>
                <?php if(!is_home()): ?>
                <li class="breadcrumb-item"><a href="#"><?php echo get_term('parcours');?></a></li>
                <?php endif;?>
            </ol>
            <h6 class="slim-pagetitle">
                <?php if(is_front_page()):?>
                    Dashboard
                <?php elseif(is_home()):?>
                    Comprendre
                <?php elseif(is_archive()):?>
                    <?php echo get_the_archive_title(get_the_ID());?>
                <?php else:?>
                    <?php if(get_post_type(get_the_ID()) == "post"):?>
                        Comprendre
                     <?php else:?>
                        <?php echo get_post_type(get_the_ID());?>
                    <?php endif;?>
                <?php endif;?>
            </h6>
        </div>
Here the content of my page

then my footer

            </div>
            <?php if(!is_admin() && is_user_logged_in() && !is_page_template('page-edit-profile.php')):?>
                <div class="slim-footer">
                    <div class="container">
                        <p>Copyright 2018 &copy; All Rights Reserved. Slim Dashboard Template</p>
                        <p>Designed by: <a href="">ThemePixels</a></p>
                    </div>
                </div>
            <?php endif; ?>
        </main>
<?php wp_footer();?>
    </body>
</html>

the way i have called swup with webpack
import Swup from 'swup';
const swup = new Swup();

**Comment by natdev** [comment]
Ok for more information on my structure @gmrchk  this is my header below
![header-screenshot](https://user-images.githubusercontent.com/24758961/56542425-706ac780-653c-11e9-816c-470937e01e98.png)

My dynamic content

and then 
![footer-screenshot](https://user-images.githubusercontent.com/24758961/56542462-909a8680-653c-11e9-8bb8-cc518a80e752.png)
my footer 

I have called my swup script this way : 
import Swup from 'swup';
const swup = new Swup();

**Comment by natdev** [comment]
my error message :
swup:animationOutStart
swup.js?ver=1.0:1263 Uncaught TypeError: Cannot read property 'innerText' of undefined
    at Swup.module.exports [as createState] (swup.js?ver=1.0:1263)
    at Swup.module.exports [as loadPage] (swup.js?ver=1.0:1074)
    at Swup.linkClickHandler (swup.js?ver=1.0:611)
    at HTMLDocument.<anonymous> (swup.js?ver=1.0:781)
module.exports @ swup.js?ver=1.0:1263
module.exports @ swup.js?ver=1.0:1074
linkClickHandler @ swup.js?ver=1.0:611
(anonymous) @ swup.js?ver=1.0:781
swup.js?ver=1.0:1279 swup:animationOutDone

**Comment by natdev** [comment]
hi @gmrchk i figured out i had just forget <title>wp_title(' ')</title> in my project thank you for your help
