### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by RFlintstone** [gmrchk/swup#135]
Hey all, I'm trying to use Swup with a combination of PHP, HTML, JS and CSS and did exactly what the instructions says but for some reason it doesn't work.
(I included certain files w/ the code but as far as I know that shouldn't be a problem)

My console says ``Uncaught SyntaxError: Unexpected identifier`` in ``main.js - line 16`` where I try to enable ``Swup`` (I installed the package w/ npm install)

```
16: import Swup from 'swup'; //This line seems to be the problem
17: const swup = new Swup();
```

Does someone know what I did wrong? Thanks in advance!
-Ruben

**Comment by gmrchk** [comment]
It seems you're missing the bundling part of your JS workflow. `import...` line shouldn't really make it to the browser and should be processed by bundler (like webpack), which would generate a compiled code for you. 

Alternatively, you can include swup from `/dist` folder with a script tag, and then you don't need to import it from npm.

**Comment by RFlintstone** [comment]
> It seems you're missing the bundling part of your JS workflow. `import...` line shouldn't really make it to the browser and should be processed by bundler (like webpack), which would generate a compiled code for you.
> 
> Alternatively, you can include swup from `/dist` folder with a script tag, and then you don't need to import it from npm.

Does it not support php? I'm trying to include it but it still doesn't seem to work.
My test repo: https://github.com/RFlintstone/page_transitions
Video that I followed: https://www.youtube.com/watch?v=mWeYMyN5-oo&t=775s

~Ruben

**Comment by gmrchk** [comment]
This has nothing to do with php actually, which is only executed on a server. The problem you are having is that syntax like `import` is not supported by a browser, so you need to bundle your JavaScript if you want to use it that way with tools like [webpack](https://webpack.js.org/) or much more beginner friendly [ParcelJS](https://parceljs.org/). Swup itself is actually bundled the same way. 

Swup [demo](https://github.com/gmrchk/swup-gia-demo), where webpack is used should be a helpful source, specifically the commands used in the scripts section of [package.json](https://github.com/gmrchk/swup-gia-demo/blob/master/package.json).

Alternatively, as already mentioned, and also used by a project in the YT tutorial, swup can be included from `dist` folder, and then the `import...` line can be left out. 

In any case, this is not a swup issue. Closing.
