### ISSUE TITLE
Integrate with Wordpress

### ISSUE THREAD

**Issue by paulzz3000** [gmrchk/swup#19]
I have tried everything to get this in WP. Driving me crazy.
http://477c1d85.ngrok.io/

**Comment by gmrchk** [comment]
WordPress includes absolute links to your pages, and those are not selected by swup's default option [LINK_SELECTOR](https://github.com/gmrchk/swup#link-selector). This #4 answer should help.

Also, you are missing definition for `.a-slide` animation, so swup will wait for animation to finish, but that will never come. Remove that class from your templates or add the definition to your CSS.

**Comment by paulzz3000** [comment]
Brilliant - thank you @gmrchk

**Comment by jcklpe** [comment]
Hey @paulzz3000 I'm attempting to do something similar and I was wondering if you might be able to point me in the right direction? I've logged a ticket here: https://github.com/gmrchk/swup/issues/44

**Comment by natdev** [comment]
Hi @paulzz3000  how did you use swup with wordpress. Can you give some example please

**Comment by jcklpe** [comment]
@natdev  You can check how I did it here: https://github.com/jcklpe/JackalopePro

**Comment by natdev** [comment]
@jcklpe i  integrated it in my project but my content just desappear. My url not updating and my content doesn't change. thanks for your help.

**Comment by natdev** [comment]
hi @jcklpe i figured out i had forget <title>wp_title(' ')</title> in my project thank you for your help

**Comment by jcklpe** [comment]
glad I could help :)

**Comment by ANONIMNIQ** [comment]
Guys, I need help integrating swup to my wordpress site. I try everything, put <main id="swup" class="transition-fade"> around content in my index.php, page.php, single.php, archive.php, search.php.. 
Create function in my function.php
`function pro_adding_scripts() {
	 wp_register_script('swup-pro-script', get_template_directory_uri() . '/swup.min.js', array('jquery'), '1.2', false);
	 wp_enqueue_script( 'swup-pro-script');
	 
	 wp_register_script('swup-pro-script2', get_template_directory_uri() . '/script.js', array('jquery'), '1.2', false);
	 wp_enqueue_script( 'swup-pro-script2');
}
add_action( 'wp_enqueue_scripts', 'pro_adding_scripts' );`

import script in header.php
`<script src="/swup.min.js"></script>
<script src="/script.js"></script>`

Use this in my script.js file:
`import Swup from 'swup';

const swup = new Swup({
 		LINK_SELECTOR: `a[href*="${domain}"]:not([data-no-swup]), a[href^="/"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup]), a[xlink\\:href]`,
 	});`

and add this css:
`.transition-fade {
  transition: 0.4s;
  opacity: 1;
}

html.is-animating .transition-fade {
  opacity: 0;
}

`
Nothing happened... when press any link page just reloads normal. I'm not sure what I doing wrong.

**Comment by jcklpe** [comment]
@ANONIMNIQ  did you check my repo linked above?

**Comment by alirexa** [comment]
Guys, can you please help me solve this problem?
I'm trying to use swup on my wordpress theme but it somehow works but it adds a "customize_changeset_uuid=" at the end of the URL.
I tried the dynamic linkselector like you mentioned [here](https://github.com/swup/swup/issues/4), the transition works but it still adds variable to the end of every URL.
