### ISSUE TITLE
Animating elements inside of the div that gets replaced

### ISSUE THREAD

**Issue by TyGoss** [gmrchk/swup#21]
It looks like currently swup only supports waiting for animations to end before going to a new page if that element exists outside of the #swup div (the div where content gets replaced.)

What you need to do is after every page load, have swup rescan the DOM for any element that has the set animation class on it and get the timing again.

That way swup knows how long to wait until the end of an animation, even on elements that were added to the page by swup itself.

**Comment by gmrchk** [comment]
That's exactly what swup does. As the content of DOM is constantly changing, swup needs to rescan the DOM at each animation. 

Do you have a code/demo where the problem was encountered?

**Comment by gmrchk** [comment]
As the suggested behavior is exactly what swup does, there is nothing to improve or fix here. The problem must be somewhere else. If you're still having trouble, feel free to get back to me.
