### ISSUE TITLE
Page Class Prefix and nav active classes not updating

### ISSUE THREAD

**Issue by davshoward** [gmrchk/swup#23]
Hi there,

Great plugin, the results are excellent. However, I can't seem to get my header to update nor am I getting the page name added in as a body class at all. The page and the rest of the content load without issue.

Any idea why?

```
<body>
    <div id="site-container" class="site-container">
        <div class="loading"></div>
        <header class="header" role="banner">
                <div class="header-logo">
                        <a href="/" aria-label="Homepage"></a>
                </div>
                <div class="global-nav-container">
                        <div class="global-nav js-global-nav">
                                <nav class="global-nav-links" data-swup="1">
                                    <a href="/" class="global-nav-link global-nav-link-home ">Home</a>
                                    <a href="/about.html" class="global-nav-link ">About</a>
                                    <a href="/contact.html" class="global-nav-link ">Contact</a>
                                </nav>
                        </div>
                </div>
        </header>
        <main class="main" rel="main">
                <div id="swup" data-swup="0">
                    ...
                </div>
        </main>
    </div>
    <script src="assets/js/swup.min.js"></script>
    <script>
        var swup = new Swup({ pageClassPrefix: 'page-' });
    </script>
</body>
```

**Comment by gmrchk** [comment]
Hi and thanks,

You need to define the elements to be replaced in [elements](https://github.com/gmrchk/swup#elements) option. If you want to replace header as well, do something like `elements: ['#swup', '#header']`. 

Page class (class attribute of body element) is taken from the templates, not added by swup. Add the classes to your static pages, and swup will replace them in the process of transition (assuming your page classes take form `page-*`, in this case... if not, you can change the `pageClassPrefix` option).

**Comment by davshoward** [comment]
Ah, gotcha. Do elements need to be IDs or is that just a preferred method?

**Comment by gmrchk** [comment]
The selectors can be any valid selector (querySelectorAll method is used for selecting).

**Comment by jesserosenfield** [comment]
My solution--

```
swup.on('contentReplaced', function() {
	var theUrl = stripTrailingSlash(window.location.pathname),
		$theCurrent = document.querySelectorAll('#header .current-menu-item'),
		$newCurrentLink = document.querySelectorAll('.main-menu-link[href*="' + theUrl + '"]');
	
	if($newCurrentLink.length > 0) {
		var $curPar = $newCurrentLink[0].closest('.main-menu-item');
		if($curPar) {
			$curPar.classList.add('current-menu-item');
		}
	}
	
	if($theCurrent.length > 0) {
		$theCurrent[0].classList.remove('current-menu-item');
	}

... ... ... 
```

**Comment by foxnoodles** [comment]
> My solution--
> 
> ```
> swup.on('contentReplaced', function() {
> 	var theUrl = stripTrailingSlash(window.location.pathname),
> 		$theCurrent = document.querySelectorAll('#header .current-menu-item'),
> 		$newCurrentLink = document.querySelectorAll('.main-menu-link[href*="' + theUrl + '"]');
> 	
> 	if($newCurrentLink.length > 0) {
> 		var $curPar = $newCurrentLink[0].closest('.main-menu-item');
> 		if($curPar) {
> 			$curPar.classList.add('current-menu-item');
> 		}
> 	}
> 	
> 	if($theCurrent.length > 0) {
> 		$theCurrent[0].classList.remove('current-menu-item');
> 	}
> 
> ... ... ... 
> ```

Thanks, this is how it should be done.

**Comment by nickpish** [comment]
Hi @jesserosenfield - thank you for your solution for managing active nav items; it's working well in my WordPress implementation. One quirk I'm noticing in my case is if I don't have a "Home" page link in my nav, when I navigate away from a different page to home, the active class will often default to the first item in the navigation (when it shouldn't be appended to any item.) If, however, I add a Home link to the navigation, it all works fine. I'm wondering how I might adjust your solution to account for this case? I have a header above my navigation that acts as the "home" link, so I don't want to duplicate it in the navigation. Thanks for any insight here!

**Comment by jesserosenfield** [comment]
@nickpish I don't think my code requires a "home" link. Provide your HTML markup for your nav menu plz and I can take a look.

**Comment by nickpish** [comment]
@jesserosenfield Thank you- here is the markup for my nav menu, as well as the JS I modified from your example. I have an element in the site header above the nav that links to the homepage (site root) and, for example, if I click on the "Sample Page" link _then_ the header element back to home, it will show the current class associated with the "Gallery" nav item, i.e. the first one. Note that this only seems to happen when navigating to that home element from a different page in the nav. Thanks for your help here.

```
<nav class="nav-primary genesis-responsive-menu" aria-label="Main" itemscope="" itemtype="https://schema.org/SiteNavigationElement" id="genesis-nav-primary" style="">
  <div class="wrap">
    <ul id="menu-primary-nav" class="menu genesis-nav-menu menu-primary js-superfish sf-js-enabled sf-arrows" style="touch-action: pan-y;">
      <li id="menu-item-25" class="menu-item menu-item-type-post_type menu-item-object-page page_item page-item-23 menu-item-25 current-menu-item current_page_item">
        <a href="http://site.local/gallery/" aria-current="page" itemprop="url">
          <span itemprop="name">Gallery</span>
        </a>
      </li>
      <li id="menu-item-6" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-6">
        <a href="http://site.local/sample-page/" itemprop="url">
          <span itemprop="name">Sample Page</span>
        </a>
      </li>
      <li id="menu-item-41" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-41">
        <a target="_blank" rel="noopener" href="https://store.com" itemprop="url">
          <span itemprop="name">Store</span>
        </a>
      </li>
      <li id="menu-item-42" class="social menu-item menu-item-type-custom menu-item-object-custom menu-item-42">
        <a target="_blank" rel="noopener" href="https://www.instagram.com itemprop=" url">
          <span itemprop="name">Instagram</span>
        </a>
      </li>
    </ul>
  </div>
</nav>
```

```
swup.on('contentReplaced', function() {
  var theUrl = window.location.pathname,
    $theCurrent = document.querySelectorAll('#menu-primary-nav .current-menu-item'),
    $newCurrentLink = document.querySelectorAll('#menu-primary-nav a[href*="' + theUrl + '"]');

  if ($newCurrentLink.length > 0) {
    var $curPar = $newCurrentLink[0].closest('#menu-primary-nav .menu-item');
    if ($curPar) {
      $curPar.classList.add('current-menu-item');
      $curPar.classList.add('current_page_item');
    }
  }

  if ($theCurrent.length > 0) {
    $theCurrent[0].classList.remove('current-menu-item');
    $theCurrent[0].classList.remove('current_page_item');
  }

});
```

**Comment by jesserosenfield** [comment]
```
function stripTrailingSlash(url)     {     
    return url.replace(/\/$/, "");
} 
```

First I would make sure to strip the trailing slash off of the url when trying to match it:

`var theUrl = window.location.pathname`

change to 

`theUrl = stripTrailingSlash(window.location.pathname)`

But your problem sounds like this is not matching an element successfully.

`$theCurrent = document.querySelectorAll('#menu-primary-nav .current-menu-item')`

which current class does your nav menu actually use??? `current_page_item`, `current-menu-item` or both???? Is your menu being generated by wordpress using PHP?

**Comment by nickpish** [comment]
Ah! Stripping the trailing slash did it! I had to add in that function, hence my leaving it out earlier, but that seems to have fixed it, thank you. And, yes, the menu is generated by WordPress w/ PHP and (annoyingly) adds both classes apparently for backwards compatibility (`current_page_item` is a relic of an older menu system, apparently; I'm only really targeting `current-menu-item` in my styles.) Thanks again.

**Comment by moritzebeling** [comment]
Just sharing my favorite way to highlight the current page:
```js
function swupActiveLinks(){
    let currentPath = window.location.pathname;
    let links = document.querySelectorAll('nav a'); // <- put your link selector here
    for (const link of links) {
        let linkPath = (new URL( link.href )).pathname;
        link.ariaCurrent = linkPath == currentPath ? 'page' : false;
    }
}
window.swup.on('contentReplaced', () => {
    swupActiveLinks(); // trigger after swup
});
swupActiveLinks(); // trigger on page load
```
```scss
nav a[aria-current=page]{
  text-decoration: underline;
}
```

**Comment by Mirkokokoko** [comment]
@moritzebeling I love this solution. Did you ever had any issues in Firefox with this? I use it at the moment and it works great, but it does not work in Firefox and I really can not see why it should not.

**Comment by gmrchk** [comment]
> Just sharing my favorite way to highlight the current page:
> 
> ```js
> function swupActiveLinks(){
>     let currentPath = window.location.pathname;
>     let links = document.querySelectorAll('nav a'); // <- put your link selector here
>     for (const link of links) {
>         let linkPath = (new URL( link.href )).pathname;
>         link.ariaCurrent = linkPath == currentPath ? 'page' : false;
>     }
> }
> swup.on('contentReplaced', () => {
>     swupActiveLinks(); // trigger after swup
> });
> swupActiveLinks(); // trigger on page load
> ```
> 
> ```css-scss
> nav a[aria-current=page]{
>   text-decoration: underline;
> }
> ```

Nice! This seems like such a common problem to deal with that it might make sense to have a little plugin to add `active` classes to the links in the navigation. There would have to be a bit of customization with options like defining the active class or the selector for nav links, but the rest seems handy to have around to drop in. 

@moritzebeling would you care to try out the new plugin template and give it a shot?

**Comment by moritzebeling** [comment]
@gmrchk okay, good idea! I tried to implement this based on the plugin starter template:

https://github.com/moritzebeling/swup-highlight-current-page-plugin

Unfortunately I don’t get my demo to run as it always prompts the error `illegal constructor` as it seems to be unable to resolve `Plugin`: https://github.com/moritzebeling/swup-highlight-current-page-plugin/blob/main/src/index.js

I have no experience in creating and testing Swup plugins nor with publishing any NPM modules and the surrounding workflow. So if anyone can point me in the right direction I would be happy to finish and publish it.

Thanks!
