### ISSUE TITLE
History back - Browser back buttons

### ISSUE THREAD

**Issue by martifenosa** [gmrchk/swup#25]
Hi,
I can't find a way to fix this, whenever one of those two methods are used the js don't run again. 
History.back() on the js or Browser back-next buttons.

Is there a way to rerun all the js or something like this?

Great work btw, I plan to use swup on all the new sites from now on.
Thanks!

**Comment by gmrchk** [comment]
Hi, glad to hear you like swup!

I see you fixed your issue. Would you mind sharing the problem/fix here, in case others run into a similar problem?

**Comment by martifenosa** [comment]
Sure! I had to use two events in order to work. Also comment the 'skipPoPStateHandling' by default.
So the final code is something like this:

` var options = {`
`    LINK_SELECTOR: 'a:not([data-no-swup]):not([target="_blank"]):not([href^="#"]):not([href^="mailto"]):not([href="' + shop_urls.cart + '"]):not([href="' + shop_urls.checkout +'"]), a[xlink\\:href]',`
`    elements: [`
`      '#swup'`
`    ],`
`    animationSelector: '[class^="fade-cover"]',`
`    cache: false,`
`    pageClassPrefix: '',`
`    scroll: true,`
`    debugMode: true,`
`    preload: true,`
`    support: true,`
`    disableIE: false,`
`  // skipPopStateHandling: function (event) {`
`   //   if (event.state && event.state.source == "swup") {`
`   //     return false;`
`   //   }`
`   //   return true;`
`   // },`
 `};`
 ` var swup = new Swup(options);`

And then: 

`var isBackButton = false;`
`$(document).on('swup:popState', function () {`
`    console.log('PopState');`
`    isBackButton = true;`
`  });`
`  $(document).on('swup:pageView', function () {`
`    console.log('Page View', isBackButton);`
`    if(isBackButton){`
`      triggerAll();`
`      isBackButton = false;`
 `   }`
 ` });`

Where 'triggerAll()' function is where I choose what to trigger depending on what page is loaded.
I don't recall exactly but I think I had to disable de cache too in order to make it work, but there is a chance I did in order to fix a completely different bug.

Hope it helps somone ;)

**Comment by gmrchk** [comment]
By default you should be able to use `swup:contentReplaced` or `swup:pageView` to attach/run your scripts, and this should work for popstate transitions as well. 

I just tried your settings with the latest version of swup and both events are triggered on back/forward buttons as well as history.back() call. 

Could you please try to update swup version and try if that fixed the error? or share your current swup version?
