### ISSUE TITLE
Page scrolling to top on form submit

### ISSUE THREAD

**Issue by MikeHarrison** [gmrchk/swup#26]
Hi,

I am just trying out swup forms, and am seeing some behaviour I would like to change if possible. I have added `data-swup-form` to a simple contact form. When submitted the page reloads through swup (fade-out,fade-in), and then scrolls to the top of the page. Would it be possible for the page to reload and stay at the location of the form, which now displays my success message?

This is the first bump I have hit with Swup, apart from this it is absolutely great 👍

**Comment by gmrchk** [comment]
Very nice point! This is a new feature which I actually haven't even used yet, so thank for a heads up.

I've added support for including a hash (id of the element) in the action attribute of the form, so the page will scroll to your form after sending and getting the reply.

```html
<form action="#form" id="form" data-swup-form>
```

I would also suggest disabling swup's scroll on submit and enabling it after the page is reloaded, so it does not move at all when sending the form. 

```javascript
swup.options.scroll = false
```

**Comment by MikeHarrison** [comment]
Thanks that's awesome! Will give it a try tomorrow. Would it be possible to elaborate a bit on the code required your second point?

> I would also suggest disabling swup's scroll on submit and enabling it after the page is reloaded, so it does not move at all when sending the form.

**Comment by gmrchk** [comment]
Sure! The easiest way to disable scrolling for forms would be...

```javascript
document.addEventListener('swup:formSubmit', event => {
    swup.options.scroll = false;
});
document.addEventListener('swup:animationInDone', event => {
    swup.options.scroll = true;
});
```
Didn't test it, hope there are no typos or something... but you get the idea.

**Comment by MikeHarrison** [comment]
Yep that was just the ticket thank you! Slight typo, final code below in case anyone else wants to do the same:

```
document.addEventListener('swup:submitForm', function() {
    swup.options.scroll = false;
});
document.addEventListener('swup:animationInDone', function() {
    swup.options.scroll = true;
});
```
