### ISSUE TITLE
Error on initial page load

### ISSUE THREAD

**Issue by glennpot** [gmrchk/swup#27]
I am getting a
 - Uncaught TypeError: Cannot read property 'addEventListener' of null
from line 918 in swup.js
 - element.addEventListener(type, listenerFn, useCapture);

I've simply added a div id="swup" and div class="a-fade" and init with var swup = new Swup() as shown in the demo to test this on my site.

What am I missing?

**Comment by gmrchk** [comment]
If I'm not missing something, that would mean `document` or `document.body` is `undefined`.
You are probably creating swup instance before the content of your page is actually parsed. 
Are you running this script in your head tag? If so, move it to the end of your body tag. 

If not, could you include the rest of the stack and your browser/OS version?

**Comment by gmrchk** [comment]
Any news on this @glennpot?
