### ISSUE TITLE
Error with CommonJS module / Browserify install

### ISSUE THREAD

**Issue by blimpmason** [gmrchk/swup#3]
Hey, I'm really excited to try this library — I've been using barba.js in all my projects for the last few years but this looks to be quite streamlined especially for use with CSS animations.

I'm having trouble installing this properly in my CommonJS module / browserify setup. Here's what I have:
```
var Swup = require( 'swup' );

var swup = new Swup({
	debugMode: true
});
```

That yields an uncaught type error:
`Uncaught TypeError: Swup is not a constructor`

When I console.log(Swup) I get the following:
```
{default: ƒ, __esModule: true}default: ƒ Swup(setOptions)arguments: (...)caller: (...)length: 1name: "Swup"prototype: {constructor: ƒ, enable: ƒ, destroy: ƒ, linkClickHandler: ƒ, linkMouseoverHandler: ƒ, …}__proto__: ƒ ()[[FunctionLocation]]: index.js:98[[Scopes]]: Scopes[3]__esModule: true__proto__: Object
```
Any ideas?

Thanks!

**Comment by gmrchk** [comment]
Hi,
that's because you're loading ES2015 module with require.

If you use ES6, you can use `import` to load the package.
```javascript
import Swup from 'swup';
```

This should also do the trick.
```javascript
var Swup = require( 'swup' ).default;
```

**Comment by blimpmason** [comment]
Got it, thanks — so does this code need to be transpiled before being used on production?

**Comment by gmrchk** [comment]
No, version of the code in npm is already transpiled.

**Comment by stgelaisalex** [comment]
I cant get it to work... 
 -- Uncaught TypeError: Swup is not a constructor -- 
<script>
        var swup = new Swup();
    </script>
