### ISSUE TITLE
is-rendering will not be removed

### ISSUE THREAD

**Issue by visiondpc** [gmrchk/swup#34]
Hi, I found out, that the is-rendering class is not removed after the new page is loaded.

This seems to happen, when .is-leaving and .is-rendering are used in CSS.

Works perfect:
`.a-fade {
    transition: .4s;
    opacity: 1;
    transform: scale(1, 1);
}

html.is-animating .a-fade{
    opacity: 0;
    transform: scale(0, 0);
}`

Does not work:
`.a-fade {
    transition: .4s;
    opacity: 1;
    transform: scale(1, 1);
}

html.is-leaving .a-fade{
    opacity: 0;
    transform: scale(0, 0);
}

html.is-rendering .a-fade{
    opacity: 2;
    transform: scale(2, 2);
}`

**Comment by josias-r** [comment]
opacity 2?

**Comment by gmrchk** [comment]
Problem is that `is-leaving` class is only used to indicate that the page is in the progress of leaving and class gets removed before the content is replaced. `is-animating` on the other hand, is removed after the content is replaced, which allows your elements to animate back in.

Replace `is-leaving` with `is-animating` in your CSS and everything should work as expected, although I am not quite sure what are you trying to achieve.

**Comment by visiondpc** [comment]
Yes, opacity: 2 is wrong und should be 0.

is-animating will not fit my needs. I want to create dirferent transition for the leaving and the appearing content. The old content should fade out and size down to 0 while the new content should should fade in and size down from 200% to 100%.

This should be possible or did I get the documentation wrong?

> is-leaving - Assigned once a link is clicked and removed right before the content is replaced. (just in case.. maybe different animations for in/out transition?)
is-rendering - Assigned right before the content is replaced and removed when the whole process of transition of pages is done. (same as above)

**Comment by gmrchk** [comment]
The animation is empowered by class changing when the content is on the page. `is-animating` is first added which allows you to animate the page out. After the content is replaced, new content is already in the "out" state, because `is-animating` class is still there. Once the class is removed, page animates back in. That does not happen with `is-leaving` or `is-rendering`. Combination of the two `.is-rendering` and `.is-animating` will do what you are trying to achieve.

```javascript
.a-fade {
    transition: .4s;
    opacity: 1;
    transform: scale(1, 1);
}

html.is-animating .a-fade{
    opacity: 0;
    transform: scale(0, 0);
}

html.is-rendering.is-animating .a-fade{
    transform: scale(2, 2);
}
```
