### ISSUE TITLE
Before cache event / where to teardown event listeners?

### ISSUE THREAD

**Issue by dylanfisher** [gmrchk/swup#36]
Hello, I was wondering if there's a good event to hook into to achieve something similar to Turbolinks' `before-cache` event listener https://github.com/turbolinks/turbolinks#preparing-the-page-to-be-cached. Or, if that doesn't already exist, would it make sense to add such an event, or achieve this in an alternate way?

Example use case:

```javascript
$(document).on('swup:pageView', function() {
  var $image = $('#my-image');

  if ( $image.length ) {
    // Resize image when the browser size changes
    $(window).on('resize.myImageSizer', function() {
      $image.width( $(window).width() );
    });

    $(document).one('swup:beforeCache', function() {
      // Need to remove the event listener when the page is cached to avoid event stacking
      $(window).off('resize.myImageSizer');
    });
  }
});
```

**Comment by gmrchk** [comment]
Hi Dylan,

To remove event listeners it's best to use `swup:animationOutDone` or `swup:willReplaceContent` event, as at that point, your content is about to be replaced as a next step and your page is most likely hidden as well.

If your question also refers to preparing the content to be cached (as `before-cache` default purpose is in Turbolinks... I think), swup caches the pages directly from the request, not before leaving the page as Turbolinks. That means there is no need for preparing the content for the cache. 
I'm guessing Turbolinks does that to preserve the state of the page even at next visit. If that's the case, I find it kind of wrong, as your javascript could do a lot of changes to the structure (possibly destructive for applying the same code at next visit). I would suggest saving the state elsewhere and applying it on `swup:pageView` event. 

The only exception when swup doesn't cache the page from the request is the initial page, which gets cached from the current DOM. If you'd make some destructive changes to the DOM at that point, it can be resolved by enabling swup before those changes.
