### ISSUE TITLE
Including absolute internal links while excluding all external links

### ISSUE THREAD

**Issue by blimpmason** [gmrchk/swup#4]
I know by default LINK_SELECTOR looks for relative links with href attributes that start with a "/", but many CMS automatically inject the full URL even when linking to a page internal to the app. 

Is there an easy way to compare current host to link target to exclude all external URLs but allow internal URLs even when they are absolute?

**Comment by blimpmason** [comment]
Thanks, the dynamic solution is perfect.

**Comment by gmrchk** [comment]
You're welcome. Thanks for the insight. I will consider changing the default options.
