### ISSUE TITLE
How to reload Javascript/Jquery after content replace

### ISSUE THREAD

**Issue by andre94** [gmrchk/swup#41]
Hi All,

Could someone give us an example to how reload javascript code after content substitution?

I'm trying to use this fantstic script with Wordpress and it works properly but, if I have some javascript inside the content replaced, it not works anymore. 

I cannot understand how to implement this code below properly
```
// load scripts for replaced elements
document.addEventListener('swup:contentReplaced', event => {
    swup.options.elements.forEach((selector) => {
        // load scripts for all elements with 'selector'
    })
});
```
----------------------

An example of code I want to reload

```
<script type="text/javascript"> // HOME
(function( $ ) {
$(function() {

document.addEventListener('swup:contentReplaced', function () {
        // ----------------------------------------
        // Particle
        // ----------------------------------------

        function Particle( x, y, radius ) {
            this.init( x, y, radius );
        }

        Particle.prototype = {

            init: function( x, y, radius ) {

                this.alive = true;

etc.....
```

Thanks!

**Comment by gmrchk** [comment]
Hi there,

I'm not sure what your code is, but what you need to do is to wrap anything you need for enabling the script (in this case `Particles`) in a function. Usually to enable a script you would use something like this.

```javascript
new Particles(element);
```

All you need to do is run the same code after the content is replaced.
```javascript
new Particles(element);
document.addEventListener('swup:contentReplaced', function () {
    new Particles(element);
});
```

You probably have more stuff that needs to be re-run, so you could wrap it all together in some init function.
```javascript
function init () {
    new Particles(element);
    // any other scripts 
}

init();
document.addEventListener('swup:contentReplaced', init);
```

Note that before enabling scripts in `init` function, you should first check whether the element is on the page. Any scripts used for elements outside of replaced blocks don't need to be re-run.

The example from docs that you have mentioned can be used when you're structuring your code into some reusable components, that are bound to a DOM element. This particular example is used with [Gia framework](https://github.com/giantcz/gia), where you could do...

```javascript
document.addEventListener('swup:contentReplaced', event => {
    swup.options.elements.forEach((selector) => {
        loadComponents( document.querySelector(selector) );   // loads all components inside of replaced block
    })
});
```

**Comment by andre94** [comment]
Hi Georgy, 

many thanks for the reply and for the script! I've implemented what you've said in this way:

1. Add id="swup" to my wp container, which is the same for all pages
2. Add class="a-fade" only for some div I've in the container that I want to be shown
3. Add a different javascript code into each page in the way you've wrote above

but when I click the link from home to portfolio, the console give me an error like

>Uncaught TypeError: Cannot read property 'getElementsByClassName' of null
    at window.particlesJS (particles.js?ver=4.9.8:9)
    at HTMLDocument.init_home (VM650:196)
    at e.exports [as triggerEvent] (swup.min.js?ver=4.9.8:1)
    at e.exports [as renderPage] (swup.min.js?ver=4.9.8:1)
    at swup.min.js?ver=4.9.8:1

due to the fact that the init_home is initialised instead of init_portfolio. Both of this function are contained in the "swup" and "a-fade" container. The result is that the portfolio page is not load properly and also init_portfolio doesn't initialised.

Any suggestion?

Really appreciated your support! :D

**Comment by gmrchk** [comment]
Don't place your scripts on each page (don't separate it). Put your scripts all together into one file and load that same file on every page, but add conditions, so the parts of your scripts are executed only when it needs to. Let's say we have some carousel on several pages, but not all...

```javascript
function init() {
    if(document.querySelector('#carousel') != null) {
        // enable carousel
    }
}


init();
document.addEventListener('swup:contentReplaced', init);
```

Any add-ons for WP running a script surely can be reloaded as well, but I would need a specific example to help you with that, and I'm not really a WP user. 

Just FYI - swup replaces the content, but it doesn't execute the scripts included in scripts tags in that content. [mergeHeadPlugin](https://github.com/gmrchk/swup#swupmergeheadplugin) can do that for script tags in the head tag, but I wouldn't recommend it.

**Comment by andre94** [comment]
Hi Georgy,

many thanks for you help on this. You have been perfectly clear. I must reconsider the implementation of this script or in general pjax functionalities with my current wordpress installation, due to the complexity behind that. 

About my javascript functions I need to load, your solution would work perfectly. The problem are the javascript functions implemented by each theme, plugin and add-ons since they are load from a lot of different javascript files or inline scripts, and intervene for all of them would require a lot of "no-efficient or clear" modifies.

Anyway, I think that the above replies and question could be helpful for other people. Many Thanks Georgy!! If I will go forward to intent this, I will let you know!

**Comment by gmrchk** [comment]
I also recommend checking [Gia](https://github.com/giantcz/gia). It's little to no code but has some simple concepts used within, which are helpful when writing reusable/modular code. When I was writing swup, my intention was to write the rest of my JS with the component approach like Gia has. Maybe you will find some inspiration... 

Glad I could help! I will close this for now but feel free to reopen if you think you have some more stuff to add/ask.
