### ISSUE TITLE
Clarifying question on installation

### ISSUE THREAD

**Issue by jcklpe** [gmrchk/swup#42]
Hi, 

Sorry, I'm a designer learning to code and I have really only previously used javascript libraries that I've imported into a project in the footer of a file. 

I've decided to make a new Wordpress theme and use webpack for it so I can start getting the hang of things. But I'm very unfamiliar with some of the new way of doing things. 

In the README you say to install just include this: `import Swup from 'swup'
const swup = new Swup()`

But I'm not clear where I'm supposed to include it? Am I supposed to include it in my footer inside a script tag? Is it supposed to go in my app.js? 

Oh... probably my app.js right? Is that right?

Also I know this is a bit old fashioned but it would be nice to be able to see a demo file or someone else's project that uses it so I know what it's supposed to do. 

So far I think I'm supposed to import swup into my app.js file, and then I think..... not sure, that I just put the swup id on the content I want to swap out? What else? I see stuff about link selectors and stuff too. But not sure about what they are meant to look like.

**Comment by jcklpe** [comment]
Okay so I think I mostly figured stuff out but I'm getting an error on build and I'm not sure what it means. Does seem to be swup related as the only thing currently declared in app.js is swup:

```
└─➤ npm run build

> jackalopepro@1.0.0 build /mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro
> webpack --mode development

Hash: f513f06c843fd9df9fd6
Version: webpack 4.19.0
Time: 3308ms
Built at: 2018-09-18 01:31:24
                          Asset      Size  Chunks             Chunk Names
./assets/css/build/main.min.css  94.3 KiB    main  [emitted]  main
   ./assets/js/build/app.min.js  8.18 KiB    main  [emitted]  main
Entrypoint main = ./assets/css/build/main.min.css ./assets/js/build/app.min.js
[./assets/css/src/app.scss] 39 bytes {main} [built]
[./assets/js/src/app.js] 3.45 KiB {main} [built] [failed] [1 error]
[0] multi ./assets/js/src/app.js ./assets/css/src/app.scss 40 bytes {main} [built]
    + 1 hidden module

ERROR in ./assets/js/src/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/scope/index.js:867:13)
    at BlockScoping.updateScopeInfo (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:364:17)
    at BlockScoping.run (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/babel-plugin-transform-es2015-block-scoping/lib/index.js:70:24)
    at newFn (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/index.js:94:17)
    at traverse (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/traverse/lib/index.js:76:12)
    at transformFile (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/core/lib/transformation/index.js:88:29)
    at runSync (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/core/lib/transformation/index.js:45:3)
    at runAsync (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/@babel/core/lib/transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ multi ./assets/js/src/app.js ./assets/css/src/app.scss main[0]
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!assets/css/src/app.scss:
    Entrypoint mini-css-extract-plugin = *
    [./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./assets/css/src/app.scss] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./assets/css/src/app.scss 98.4 KiB {mini-css-extract-plugin} [built]
        + 1 hidden module
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! jackalopepro@1.0.0 build: `webpack --mode development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the jackalopepro@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/david/.npm/_logs/2018-09-18T07_31_25_406Z-debug.log
```

And then I get a type error flag for TS in app.js itself that reads as follows:

"Cannot find a declaration file for module 'swup'"

And here's the error log: 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle jackalopepro@1.0.0~prebuild: jackalopepro@1.0.0
6 info lifecycle jackalopepro@1.0.0~build: jackalopepro@1.0.0
7 verbose lifecycle jackalopepro@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle jackalopepro@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro/node_modules/.bin:/home/david/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler:/mnt/c/Python37/Scripts:/mnt/c/Python37:/mnt/c/ProgramData/Boxstarter:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/Microsoft VS Code/bin:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/Git LFS:/mnt/c/Program Files/nodejs:/mnt/c/Program Files (x86)/Yarn/bin:/mnt/c/Program Files/TortoiseGit/bin:/mnt/c/Users/David/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/David/AppData/Local/Pandoc:/mnt/c/Users/David/AppData/Roaming/npm:/mnt/c/Users/David/AppData/Local/hyper/app-2.0.0/resources/bin:/mnt/c/Users/David/AppData/Local/GitHubDesktop/bin:/snap/bin
9 verbose lifecycle jackalopepro@1.0.0~build: CWD: /mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro
10 silly lifecycle jackalopepro@1.0.0~build: Args: [ '-c', 'webpack --mode development' ]
11 silly lifecycle jackalopepro@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle jackalopepro@1.0.0~build: Failed to exec build script
13 verbose stack Error: jackalopepro@1.0.0 build: `webpack --mode development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid jackalopepro@1.0.0
15 verbose cwd /mnt/c/Users/David/Work/Code/JackalopePortfolio/Pro/apps/wordpress/htdocs/wp-content/themes/JackalopePro
16 verbose Linux 4.4.0-17134-Microsoft
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error jackalopepro@1.0.0 build: `webpack --mode development`
22 error Exit status 2
23 error Failed at the jackalopepro@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by gmrchk** [comment]
Hi @jcklpe,

You should be able to try swup without webpack, if you include the swup with the script tag. That should get you going for a start.

The issue you are having with webpack is most likely not swup related (probably babel-loader, maybe [this](https://stackoverflow.com/questions/52092739/upgrade-to-babel-7-cannot-read-property-bindings-of-null) will help?), so I can't really help you with that. 

Also, version of swup on npm is already transpiled, so if that's the only thing you are trying to compile, running webpack without any config file on your entry point (app.js) should work just fine. 

I would suggest to go slower, forget about all the plugins for minification of css, etc. and try to get going with your scripts for now. It can get overwhelming really quick with tools like webpack. The less you put into your setup now, the less likely you will encounter some error you won't understand. Or if you're starting with JS all together, maybe leave out any setup at all and see where it gets you. 

As there is no swup issue here, I will go ahead and close this for now.

Cheers!

**Comment by jcklpe** [comment]
@gmrchk  Hmmm, I'm not sure, as when I don't have swup included I don't have any issues running my npm build, and as far as I can tell the primary issue is that swup is throwing that type error. Here's a picture:

![image](https://user-images.githubusercontent.com/9451726/45720826-52cf1d00-bb6b-11e8-9abd-f8ec948cce61.png)

I'll try integrating it just as a script though.

**Comment by gmrchk** [comment]
That's a TypeScript error. I'm not sure that it's related to the previous error, but it could definitely prevent build.

As far as I know, TypeScript only lets you compile the code with valid variable types (or maybe can be switched to only show warning on compile). Anyway, as there is no definition file for swup (the file where all the types of variables are defined) for TS, it cannot check what types are expected. I'm pretty sure you can create the definition file on your own somehow, but I would have to look into that.

**Comment by jcklpe** [comment]
@gmrchk I checked that link and I'm pretty sure that was indeed the problem! Thank you!

I'm not sure why it's asking for typings for swup though as it's a JS project right? And I've got it saved in a JS file. But maybe that's because of the babel issue. I'll let you know after this thing is done installing the proper modules. 

Thank you for the response :)

**Comment by jcklpe** [comment]
Yes! It does indeed work now. Thank you so much for the help! I feel like I have so much catching up to do and webpack is something I've been putting off learning for awhile. But I think now that I've gotten over some of these first install hiccups (which mostly seem to stem from Webpack 4 being so new) I'm going to be good to go!

**Comment by jcklpe** [comment]
# Hurray! Got it working. 

I started writing out another comment after not being able to get stuff to work. But through the process of writing stuff out I was able to figure out what additional avenues I should check, and I got it working! Woohoo! 

I'm leaving the below comment I started writing as documentation in case anyone else runs into similar issues. 


Okay I've checked and double checked and as far as I can tell the structures between my index.php and my single.php page are identical. Still wasn't working so I thought maybe I was missing something. But I noticed this error in console:

```
Element #swup is not found in cached page.
uncaught exception: /wordpress/wp-admin/post.php?post=21&action=edit
```
I don't know if the first error is related to the first, but from the first I think I can gather that it is saying that it can't find a swup element on the page that it thinks it should be cacheing and preparing for animation. I don't see how that's possible. Because there is a swup on both pages. 

Here's a straight copy paste of index.php:

```
get_header(); ?>
<main id="swup" class="site-content-contain">
	<div id="content" class="a-fade site-content">
		<div class="case-study wrap">
			<?php if ( have_posts() ) :
				/* Start the Loop */
				while ( have_posts() ) : the_post();?>
					<section class="case-study-box">
						<a class="text-container" href="
						<?php the_permalink(); ?>">
							<h2 class="case-study-title">
								<span><?php echo get_the_title(); ?></span>
							</h2>

							<h3 class="case-study-subheading">
								<span><?php echo get_field( "case_study_subheading" ); ?></span>
							</h3>

						</a>

						<div  class="overlay" style="<?php echo get_field( "overlay_background_grad" ); ?>"></div>

						<img src="<?php $imageLocation = get_the_post_thumbnail_url(get_the_ID(),'large'); echo $imageLocation; ?>">

					</section>
				<?php endwhile;

				else : ?>
					<p>There are no posts</p>
			<?php endif; ?>
		</div>
		<!-- case -study-wrap-->
	</div>
	<!--site content-->
</main>
<!-- main swup-->

<?php get_footer();

```
And here is a straight paste of single.php

```
get_header(); ?>
<main id="swup" class="site-content-contain">
	<div id="content" class="a-fade site-content">
		<div class="wrap">
			<div id="primary" class="content-area">
				<div id="main" class="site-main" role="main">

					<?php
						/* Start the Loop */
						while ( have_posts() ) : the_post();
							get_template_part( 'template-parts/post/content', get_post_format() );
							// post navigation template part
						endwhile; // End of the loop.?>
				</div>
				<!-- site-main-->
			</div>
			<!-- primary-->
		</div>
		<!-- wrap-->
	</div>
	<!--site- content-->
</main>
<!-- main swup-->

<?php get_footer();

```

As you can see they both have a `<main id="swup">` and those tags with the swup ids are in identical places in the hiearchy of the page. And I can confirm this also in relation to their place with the body and head tags too etc, as you can see here:

![image](https://user-images.githubusercontent.com/9451726/45914151-8aa5c100-be06-11e8-9651-4ec0059451dd.png)

![image](https://user-images.githubusercontent.com/9451726/45914156-9d1ffa80-be06-11e8-9017-cafb229c3aea.png)


I'm thinking the issue is that it's not properly able to guess what pages it should cache because it's not selecting the links correctly, perhaps? 

But I replaced the default link selector in the swup.js file so not sure why that's not working. 

FIXED: WOO! Okay so I decided to double check the link selector stuff and I found that if I just used this following solution it fixed the issue for me! 😄 

```
const domain = window.location.origin

const swup = new Swup({
    LINK_SELECTOR: `a[href*="${domain}"]:not([data-no-swup]), a[href^="/"]:not([data-no-swup]), a[href^="#"]:not([data-no-swup]), a[xlink\\:href]`,
})
```
