### ISSUE TITLE
Use API to scroll to specific anchor

### ISSUE THREAD

**Issue by tomassams** [gmrchk/swup#49]
Hi,

Is there a way to use the swup API to use the swup scroll functionality to scroll to anchors, without it being triggered by a link to that anchor? E.g. triggering the scroll with my own scripts or other actions.

**Comment by gmrchk** [comment]
Hi, sure!

```javascript
swup.scrollTo(document.body, 2000);    // scrolls to position 2000 from top
```
Add the position of your element from top, and you're good to go.

**Comment by tomassams** [comment]
Thanks, that works perfectly!
