### ISSUE TITLE
Updating classes on elements outside of the #swup container

### ISSUE THREAD

**Issue by blimpmason** [gmrchk/swup#5]
Is there a way to update classes on DOM elements outside of the #swup container based on the new page? For example to reset the active link in a header menu.

Thanks again!

**Comment by gmrchk** [comment]
Of course! In the code that handles your header/menu (I'm guessing you separate your code in some way), simply update the state anytime after the URL is changed based on swup [events](https://github.com/gmrchk/swup#events).

For this example, you could use the current URL as an indicator for the active link, as the `href` of the link would be the same as `window.location.pathname`. You could do something like:
```javascript
document.addEventListener('swup:contentReplaced', event => {
    // 1. remove active class from all links
    // 2. go through all links and add active class if href == current URL
});
```
Similarlly, you can for example use `swup:clickLink ` event to trigger close of menu on mobile.

If you would like to actually access the new page and do something based on the content, I would suggest to do that the same way, after the content is placed into DOM.

**Comment by blimpmason** [comment]
Nice, thanks — I ran this code on the barba.js new page ready event:

```
// Update classes for elements flagged with "data-barba-update" attribute
		var updateElements = $(newPageRawHTML).find('[data-barba-update]') // New ones
		$('[data-barba-update]').each(function(index) {
	        var newClasses = $(updateElements[index]).attr('class');
	        $(this).attr('class', newClasses);
```

Is the new page HTML accessible before the contentReplaced event fires? It's nice to get instant feedback (as on clickLink), but I'm hoping for something more flexible that could be used to update other elements outside of the #swup container as well.

**Comment by gmrchk** [comment]
No problem!
The content of any page is accessible in cache when it's loaded and you can detect that based on `swup:pageLoaded` or `swup:pagePreloaded`, but you can't jump in before the content is replaced in DOM and modify it (or you could directly in cache, but that would just create a mess). 

I'm sensing that you would like to modify different parts of the page from the received one. In swup, you can define as many elements that you'd like to replace as you want, not just one container. That should solve your issue. In case that's not the issue, please be specific.

**Comment by blimpmason** [comment]
Ahhh, I totally missed that you can define multiple elements for swup to replace! That's exactly what I'm looking for. Elements that need to be swapped outside of the main container could be selected with a data attribute like data-swup-update, with no animation specified so the swap is instantaneous.

**Comment by blimpmason** [comment]
That's working great except for one thing — the change is not instant onclick, it's time with the reveal of the new page. Is there anyway to let some elements update instantly without waiting for animations to complete?

**Comment by gmrchk** [comment]
Nope, the animation is also there to buy some time for the next page to load. Page can't be replaced if it's not loaded and all of it's parts are replaced at the same time.

If you want to change some visual part of your page right after click (like the active link in menu), while the next page is loading, you can use [classes assigned on html element](https://github.com/gmrchk/swup#example-of-different-transitions-for-different-pages), where classes based on routes are used as well. 

For menu links you could also just force hide the active state for all of them during the process of page transition (based on `is-changing` class).

**Comment by gmrchk** [comment]
I'm guessing this is resolved. If not, feel free to reopen.

**Comment by blimpmason** [comment]
Thanks and sorry for the slow response, these are good solutions. I think binding to the swup:clickLink event will come closest to the experience I'm looking for.
