### ISSUE TITLE
Swup fade in effect on initial site load

### ISSUE THREAD

**Issue by h0rhay** [gmrchk/swup#51]
Hey guys is this possible?

**Comment by dougkeeling** [comment]
@h0rhay Not that I am aware. I was looking to do this as well, and ended up manually fading things in on the first `window.load`. Seems to work well since it's only used on the first page people visit.

**Comment by gmrchk** [comment]
Hi, swup usually "kicks in" after the page has loaded, so this is not really for swup to do. However, as @h0rhay is proposing, you can do this in many ways without swup being involved. Probably the easiest way is having `is-animating` class on `html` tag at load, and removing it with JS once the page has loaded. 

However, you should consider that not all users have JS enabled in the browser, although the number is very small for most of the sites.
