### ISSUE TITLE
proposal: LINK_EXCLUDE_SELECTOR

### ISSUE THREAD

**Issue by panayotov** [gmrchk/swup#52]
I have a proposal: adding **LINK_EXCLUDE_SELECTOR** option, with selector that if matched, will disable swup. Example: a[href^="mailto"], '.should-refresh' etc.  I know one can add *data-no-swup* attribute, but It's not always possible.

**Comment by thetoine** [comment]
@panayotov you can add combination to query to ignore specific item, like this : 

```js
a:not([href^="mailto"])
```

**Comment by gmrchk** [comment]
As @thetoine mentioned, [LINK_SELECTOR](https://github.com/gmrchk/swup#link-selector) offers this functionality. I think another option for excluding links would be rather confusing than helpful.
