### ISSUE TITLE
Swup for initial page load

### ISSUE THREAD

**Issue by MikeHarrison** [gmrchk/swup#55]
Hi,

Loving Swup for giving my page transitions that bit of style - thanks for all your work on it.

Is there any way I could leverage that Swup awesomeness for my initial page load when someone first arrives at my site?

**Comment by gmrchk** [comment]
Hi @MikeHarrison, thank you! Definitely hit me with a link if you'd like to share your work! I'm curious what people come up with while having that little creative boost from swup. 

This should help you with your issue #51.

**Comment by MikeHarrison** [comment]
Thanks! I need a solution with a no-js fallback, so will have a play and see what I come up with.

**Comment by gmrchk** [comment]
Having a "no-js" class at load and removing it in your head tag with JS should give you enough control in CSS, so you could just "force display" all the elements when that class is there.
