### ISSUE TITLE
Swup events visual guide #enhancement

### ISSUE THREAD

**Issue by panayotov** [gmrchk/swup#57]
Hi all, I have proposition for enhancement:

Adding a Visual guide ( similar to [Vue transition classes guide (https://vuejs.org/v2/guide/transitions.html#Transition-Classes) ) . Although there is **debugMode** option, the flow and sequence of the events is unclear from the docs. 

For example, how to listen for animationStarts event ? adding swup:animationInStarts and swup:animationOutStarts events would make it more clearly what happens after what.

**Comment by ronaldohoch** [comment]
+1 :D

**Comment by gmrchk** [comment]
Adding `swup:animationInStarts` and `animationOutStarts` sounds reasonable. I will do that!

Can you elaborate some more on the visual guide? What does it do exactly? Is it just about the extra classes? 

We could create a plugin for debugging, with custom on-page console, settings, and stuff... As it would be plugin loadable only for debugging purposes, we wouldn't really be limited by size and could go crazy with what it can do (displaying suggestions or possible causes for a problem...). 

Is that what you have in mind?

**Comment by panayotov** [comment]
I'm currently using SwupJS in a project and there are some scenarios that are unclear and such a visual guide would help with. So let's start:

I have several types of transitions, depending on from what to what page I'm going to.  Instead of component - based approach ( similar to Gia ) I'm using page-controller based approach ( similar to HighwayJS ). I need to pass these controllers appropriate HTML and I do this by getting some content on Swup events. Here is some code:

```
import Page from './page';
import $ from "jquery";

const pageSelector = '#page-content';

class Pages {
	constructor() {
		this.pages = {};			
		this.prevPage = null;		
		this.currentPage = null;
	}

	registerPage(namespace, page) {
		this.pages[namespace] = page;
	}

	registerPages(pages) {
		$.each(pages, (key, page) => this.registerPage(key, page));
	}

	getPage(namespace) {
		const pageController = this.pages[namespace];
		if (pageController && $.isFunction(pageController)) {
			return pageController;
		}
		return Page;
	}

	init() {
		document.addEventListener('swup:pageView', (event, a) => {
			if (this.currentPage) {
				this.prevPage = this.currentPage;
				this.prevPage.emit('destroy');
			}
			const pageEl = $(pageSelector);
			const pageNamespace = pageEl.data('page');
			const pageController = this.getPage(pageNamespace);
			this.currentPage = new pageController();
			this.currentPage.emit('onEnter');
		});

		document.addEventListener('swup:animationOutDone', event => {
			this.prevPage && (this.prevPage.emit('onLeaveCompleted'));
		});

		document.addEventListener('swup:animationInDone', event => {
			this.currentPage && (this.currentPage.emit('onEnterCompleted'));
		});

		document.addEventListener('swup:clickLink', event => {
			bus.emit('close:nav');
		});
	}
}

export default new Pages();
```

I had some problems with getting the HTML from **pageSelector** on different swup events. So for example if going from page **/A** to page **/B** how I know the user navigated to a page? Should I use _swup:clickLink_ event, and what when user navigates via history entries?  

I think what could be done is visual guide, explaining the lifecycle of page transition for two pages:

Browser loads page **/A**
Dispatched swup:pageView event,


User goes to **/B**  ( link clicked ) 
Dispatched _swup:willReplaceContent_ . Replace content, old content removed from Dom, diapatched _swup:contentReplaced_ . 

Visualised this way, everybody can understand the lifecycle hooks and decide how to structure it's code ( components, controllers, etc ) from just viewing the diagram. The **debug** option is very helpful, but I think it's hard to see the lifecycle of page transition just from reading logs. 

I can try to prototype of such a visual guide and post it here for community review.

**Comment by gmrchk** [comment]
Sounds awesome! Let's start with your prototype and see where this takes us. The diagram could take a form of a tree of some sort, or are you thinking of some other form?

As I wrote swup, it is very hard for me to realize what is or isn't clear to others, so thank you for your help!

**Comment by Geestig** [comment]
+1 

Would be great to see a quick summary of classes that are being applied and in which order. It's kind of difficult now without making certain animations ungodly long for testing purposes.

**Comment by gmrchk** [comment]
@Geestig just FYI, you can slow down all the animations for debugging with [Chrome animation panel](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/animations).

**Comment by gmrchk** [comment]
Hi, 

I have added animationInStart and animationOutStart events to make the sequence of events clearer. 

Is there any progress on the prototype of the visual guide by any chance? 

One thing that hit me while thinking about it is that the sequence of events is not really that static in swup. For example, `scrollStart` and `scrollDone` events may be triggered right after each other in case swup has nowhere to scroll, so `scrollDone` may happen before or after `animationInDone`. 
A similar thing applies to `animationOutDone` event and `pageLoaded`, where it's not fixed what happens first. In general, many things are happening in parallel in swup, which I think is great, but I understand that it can cause confusion. 

Do you guys think a simple diagram of possible sequences could help?

**Comment by gmrchk** [comment]
Hi guys,

What do you think about this? Would something like this help with a little intro about swup events being quite dynamic?

![events](https://user-images.githubusercontent.com/9338324/50060754-2346a580-0198-11e9-9591-d9be67b98ad6.png)

Events in bold font get a propagated native event in the handlers registered with **on** method.  
Groups of events next to each other on the X axis are different scenarios of what's happening.  
The scroll can start and end at multiple times in the transition lifecycle, so it's just completely aside. 

I'm pretty sure this still doesn't cover all the possible scenarios.

**Comment by daun** [comment]
2023 Update — we've just released [swup 4](https://swup.js.org/announcements/swup-4/) and the docs now include a handy [lifecycle diagram](https://swup.js.org/lifecycle/#lifecycle-diagram).
