### ISSUE TITLE
[Question] is there a way to call swup manually?

### ISSUE THREAD

**Issue by h0rhay** [gmrchk/swup#59]
My setup has JS running with onClick events  that then use window.location to load new pages
Is there a way to use like a swup.navigate event, instead of window.location?

Thanks

**Comment by h0rhay** [comment]
I tried `swup.loadPage` .. but it doesn't work for me..
I never see the `html.is-animating` class appear..

**Comment by gmrchk** [comment]
Hi!
swups `loadPage` method is exactly what you're looking for. 

Usage:
```javascript
swup.loadPage({url: "/your-new-url"})
```
You can try it out in the console. If that doesn't work for you, there should be some error showing up.
