### ISSUE TITLE
Transitions don't appear to be animating. 

### ISSUE THREAD

**Issue by jcklpe** [gmrchk/swup#60]
Hey, sorry to be asking such a basic question here, you've been doing an awesome job Georgy and I don't want to be taking away your valuable time but I seem to have run into some problems. 

I got swup working fine and then I proceeded to work on the rest of my website. Somewhere along the way I would notice that the transitions didn't seem to be working, though sometimes they would. I couldn't really figure out what was causing it, it seemed really inconsistent so I chalked it up to a problem that I would fix once I got the rest of the site done. 

I finished the rest of the site (well mostly) and I decided to tackle getting swup properly loaded into my website via webpack instead of loading the dist manually. Before I started doing that though I started clicking around and saw that the transition animation was basically never happening. I tried to load it via webpack to see if I could fix it that way. That didn't work. I tried going back to the original way I was loading it, and that didn't work either. When I loaded the dist pack directly, I also updated my npm packages etc and made sure to load the 1.33 dist (I had previously been using 1.2 or something). 

So I know that I'm using the latest version. I also know that swup is loading correctly and running correctly because I see "swup enabled" being added to the `<html>` 

But when I transition between one page and another I don't see any animation. I do see a scroll up animation after stuff has loaded but nothing else. 

Here's what one page looks like: 

(Github is acting weird and won't let me upload images. I'm also uploading images instead of code because I'm trying to show the way stuff is actually being rendered in the DOM)

https://i.imgur.com/8FWoeZx.jpg
and 
https://i.imgur.com/Kd9WVTo.png

Any clue why this might be happening?

Also does anyone else have this working in wordpress with webpack loading etc? I've been getting a type error when I've tried to do that since I filed https://github.com/gmrchk/swup/issues/42 but checking back in today I still don't see why it's not loading through webpack correctly.

**Comment by jcklpe** [comment]
Okay so I've decided to try adding in a different kind of animation (a move in, instead of just a fade) and it's started working again, Idk why though. Even so, it's animation is very very choppy. 

Also I see this in the console? 

`Load denied by X-Frame-Options: https://vk.com/ does not permit framing.`

What's that mean? My understanding of that message in console is that Mozilla is refusing to do cross site scripting from vk.com but.... why would the script be loading anything from vk.com?

**Comment by jcklpe** [comment]
Transitions are much less choppy on Chrome than they are on Mozilla. What could be causing that?

**Comment by gmrchk** [comment]
Hey @jcklpe,

If I understand correctly, you figured out that your transition was there all along, but it was too choppy to actually see any animation, correct?

To inspect your animation, I like to use [chrome animation inspector](https://developers.google.com/web/tools/chrome-devtools/inspect-styles/animations), which lets you slow down everything and stuff, definitely recommend that!

Regarding Firefox, it's having a lot of troubles when it comes to animation. Some things I noticed lately:

* While it was always a bit slower when it comes to animation compared to chrome, it seems they introduced a whole bunch of new animation-related issues with quantum. I guess that redesigning engine for multiple CPU cores doesn't play well with integrating graphics card into the process...?
* Handles animation of big blocks terribly.
* Have a big problem with retina displays.
* Have a big problem with animating SVGs.
* While optimizing animation (using transform, opacity...) helps drastically in Chrome, for FF it looks like it doesn't help at all.

What worked for me in different cases for FF:

* Optimising animation, changing speed and easing. Playing around with it till you're happy with it really...
* Animating with JS can help a lot. You can optimize the animation yourself or use tools like [GSAP](https://greensock.com/gsap) to do it for you.
* Canvas seems to work nicely even on FF (but that's rather for animating SVGs and stuff, not a content).

**Comment by jcklpe** [comment]
hi yes @gmrchk I think the issue basically just came down to an issue with FF. I'll close this ticket as fixed. 

Also I figured out how to get my webpack stuff working. It was just a simple syntax issue on my part, because I'm still so new to JS. It's working great now! Thanks!
