### ISSUE TITLE
Double vertical scrollbar

### ISSUE THREAD

**Issue by Geestig** [gmrchk/swup#61]
First of all, great plugin! I really enjoy using as it's straightforward and does what it's supposed to. However I have a tiny issue when changing pages. Whenever someone changes page a secondary vertical scrollbar shows up. This mainly seems to be the case for people using Chrome. I've tried the following:

html.is-changing {
	overflow:hidden;
}

Adding this is a little fix but isn't optimal as you can't scroll while it's animating and it causes a little stutter when the scrollbar returns. Are there any possible solutions to this?

::-webkit-scrollbar {
display: none;
}

Is a dirty fix to remove all scrollbars entirely

![screenshot 2018-10-10 at 10 33 54](https://user-images.githubusercontent.com/9035369/46723513-55a7c400-cc78-11e8-96d7-7854ad216e13.png)

**Comment by gmrchk** [comment]
Hi and thanks!

I checked chrome/FF on WIN and I can't seem to replicate your problem on any of my projects. I think it's something CSS specific to your project. Are you adding some kind of height and/or overflow on body, html or some wrapper in your page?

**Comment by Geestig** [comment]
I've tried playing around with heights / overflows / etc. It only happens when you put the following option on:
![image](https://user-images.githubusercontent.com/9035369/46814897-021d9f00-cd7a-11e8-8c8d-d221e121e0dc.png)

Which is under general in your system preferences.

**Comment by gmrchk** [comment]
Still no luck getting the same behavior. Any chance you can post a demo of a project where this is happening?

**Comment by Geestig** [comment]
Not really since I currently disabled the scrollbar entirely as a temporary fix... I'll try looking for the problem a bit more.

**Comment by gmrchk** [comment]
Hi @Geestig, 

could you please share what was wrong/how did you resolve the issue?

**Comment by Geestig** [comment]
@gmrchk haven't had time yet to check it further.

**Comment by Geestig** [comment]
@gmrchk 

Just had the time to check it out. And apparently there was a site-wrapper which had max-width: 100vw and overflow-x: hidden on it which made the transitions freak out. 

Thanks for the quick replies!

**Comment by gmrchk** [comment]
I think when you set one of the properties (x/y) of overflow, the other is automatically set to "auto", which was probably the problem here. 

Thanks for getting to the bottom of this... for future reference.

I'm glad to help!
Cheers
