### ISSUE TITLE
page-specific CSS file loading late after transition

### ISSUE THREAD

**Issue by srikat** [gmrchk/swup#63]
Hello,

I am trying to use swup on a WordPress site running [Oxygen](http://oxygenbuilder.com) here:

https://oxygen-swup.wpdemos.net/

Oxygen loads page-specific CSS on the pages like this:

```<link rel='stylesheet' id='oxygen-styles-css' href='https://oxygen-swup.wpdemos.net/?xlink=css&#038;nouniversal=true&#038;ver=4.9.8' type='text/css' media='all' />```

```<link rel='stylesheet' id='oxygen-styles-css' href='https://oxygen-swup.wpdemos.net/about-us/?xlink=css&#038;nouniversal=true&#038;ver=4.9.8' type='text/css' media='all' />```

and so on..

After adding swup, when any link in the nav is clicked the page content loaded fine but devoid of styles.

Next, I added the swupMergeHeadPlugin plugin.

Here's the current code:

```
var options = {
    plugins: [
        swupMergeHeadPlugin
    ]
}

const swup = new Swup(options);

swup.usePlugin(swupMergeHeadPlugin, {runScripts: "true"});
```

While this does make the above page-specific CSS to load, it is happening after we see a flash of unstyled content for a brief moment.

Any advice on tackling this is appreciated.

**Comment by gmrchk** [comment]
Hi,

FYI, you don't need to use options as well as `usePlugin` method to use a plugin. `usePlugin` method is there in case you'd like to change default options, so if you'd like to run scripts in the head tag, this will do:

```javascript
const swup = new Swup();
swup.usePlugin(swupMergeHeadPlugin, {runScripts: "true"});
``` 

And to your issue... Problem is that oxygen puts all the styles used on that page into one file, even general styles used across all pages as styles for header, the main layout and so on... That means that swup removes all styles (except the styles for atomic classes that are present in all pages) and replaces them with new ones, which takes a while for a browser to process. Ideally, any general styles reused across pages (including the styles used for swup animation) should be put in a separate file that is loaded in all pages (so it doesn't get replaced by swupMergeHeadPlugin).

**Comment by srikat** [comment]
Thanks for the reply and your time.

I sent them a support ticket regarding this.

I'll reopen this if/when there is an update.

**Comment by coli21** [comment]
I'm trying to integrate swup with Oxygen and i have the same issue. Any update?

Btw, i can't find swupMergeHeadPlugin anymore. 🤔

**Comment by wdaellenbach** [comment]
@srikat the SwupHeadPlugin can be used to update <head>, and persisting stylesheet tags ensures that there is no FOUC between transitions.

only issues I have now are build up of many #oxygen-styles-css link tags and a delay between DOM contents being loaded and styles from the newly loaded sheet being rendered

`new SwupHeadPlugin({
			  persistTags: 'link[rel=stylesheet]',
			}),`
