### ISSUE TITLE
Other scripts on loaded page 

### ISSUE THREAD

**Issue by logoswind** [gmrchk/swup#64]
Great work , thanks ! 

My question may sound quite rookie , however I am sure someone else may have same question as well.
Once Swup completes the transition of page A to B  , after  XX ms  I'd like to have other css formations to happen as well ( screw , rotate , change colour etc ) .

to make it much clearer , currently I have other JS's are making parallax effects on elements on page load .But I'd like to keep those elements still part of transition done by Swup .

**Comment by gmrchk** [comment]
Hi @logoswind,

any chance you can provide some code example/demo/image of what you have in mind? I'm not sure I understand what is it that you want to achieve.
