### ISSUE TITLE
Loading scripts after swup:contentReplaced issue

### ISSUE THREAD

**Issue by adstyles** [gmrchk/swup#68]
Hi Gregory,

First of all, loving SWUP, it's brilliant.

I've discovered a bug, but would like to see what you think.

I have certain scripts, wrapped up in a scriptInit(); function that I load on each page. Within that function I have tests on the body class, so e.g. if we're on the homepage, fire a function.

The problem I have is in using swup:contentReplaced to fire this script, as it is still testing the previous body classes and not the new page. It appears the body classes are updated after the swup:contentReplaced event, so the only work around I found is using a setTimeout of (1mili second).

I've made an example, see below:

```
var scriptInit = function(){
 if( $('body').hasClass('home') ){
    console.log('we\'re on the homepage');
  };
};

document.addEventListener('swup:contentReplaced', event => {
    console.log($('body')); // gets previous page
    setTimeout(function(){
      console.log($('body'));  // gets new page
      scriptInit();
    }, 1);
});
```

Is there a better event to use? Or is there a reason the body classes are updated after swup:contentReplaced ?

**Comment by gmrchk** [comment]
Hi, thank for the nice words!

You are correct and there is no reason for this, just a bug. Fixed in v1.4.3. Please update swup. 

Thanks and good job!
