### ISSUE TITLE
Can swup handle page fragments?

### ISSUE THREAD

**Issue by o-o-o-o-o** [gmrchk/swup#70]
I am currently using pjax to load  a specific div in my target page, does swup have the same functionality?

**Comment by gmrchk** [comment]
Swup is intended to enhance a static website. That means that if your site works without JS, it will work with swup just fine (and most likely much better with the possibility for cache, preload, etc...). You can define as many containers that swup needs to replace as you want and swup will always replace the contents of all of them .

If you'd like to replace just one of the containers for some reason (now I'm assuming you don't animate anything at all and just use swup to replace content), you can theoretically create more instances of swup with separate containers and different [LINK_SELECTORS](https://github.com/gmrchk/swup#link-selector). Keep in mind that it's not recommended (and I have never tried it).
