### ISSUE TITLE
Pass page class to swup.loadPage options

### ISSUE THREAD

**Issue by panayotov** [gmrchk/swup#71]
Hi all,
I have a website with different page transitions "work" > "work" for example uses one transition, "*" > "work" - another. I need to programatically navigate these pages ( for example going from work to work when user interact with canvas , so no page links ). I use `swup.loadPage({ url, data })` to navigate. I can't see option to pass to which page I'm navigating to ( this would be data-swup-class if link element ). I think it would be a useful option to be added.

**Comment by gmrchk** [comment]
Hi,

I agree, moving this functionality into a `loadPage` method and providing an interface this way sounds great! I would also suggest changing the name of the data attribute to something more descriptive like `data-swup-transition` while we're at it.

**Comment by gmrchk** [comment]
swup and swupjs both support this in latest versions with `customTransition` [argument used for this](https://github.com/gmrchk/swup#api). 

Name of data attribute used to define the name of transition on links has been also changed to `data-swup-transition`.
