### ISSUE TITLE
data-swup-form not transmitting data

### ISSUE THREAD

**Issue by Geestig** [gmrchk/swup#73]
Alright, so I added a data-swup-form to my form which is used to filter content. However when submitting the form the page redirected and all the parameters get added but they do not have a value. I'm not sure if this one is on me or some bug.

```
<form method="get" action="{{craft.entries.id(1019).one().url}}" class="w-5/6 mx-auto bg-grey-light h-24 -mt-12 z-20 relative flex items-center justify-center filter-form" data-swup-form>
		<input class="mr-1 h-10 text-blue-dark font-bold text-sm pl-4 w-auto w-1/4" type="text" placeholder="Gemeente" name="city" id="city" {% if craft.app.request.getParam('city') %} value="{{craft.app.request.getParam('city')}}" {% endif %}>
		<select name="type" id="type" class="mx-1 h-10 text-blue-dark bg-white font-bold text-sm pl-4 w-auto w-1/8">
			<option value="0" {% if craft.app.request.getParam('type') == 0 or craft.app.request.getParam('type') is empty %} selected="selected" {% endif %}>Type</option>
			<option value="1" {% if craft.app.request.getParam('type') == 1 %} selected="selected" {% endif %}>Te Koop</option>
			<option value="2" {% if craft.app.request.getParam('type') == 2 %} selected="selected" {% endif %}>Te Huur</option>
			<option value="3" {% if craft.app.request.getParam('type') == 3 %} selected="selected" {% endif %}>Over te nemen</option>
		</select>
		<input class="mx-1 h-10 text-blue-dark font-bold text-sm pl-4 w-auto w-1/8" type="text" placeholder="Max. Prijs" name="price" id="price" {% if craft.app.request.getParam('price') %} value="{{craft.app.request.getParam('price')}}" {% endif %}>
		<input class="mx-1 h-10 text-blue-dark font-bold text-sm pl-4 w-auto w-1/8" type="text" placeholder="Slaapkamers" name="bedrooms" id="bedrooms" {% if craft.app.request.getParam('bedrooms') %} value="{{craft.app.request.getParam('bedrooms')}}" {% endif %}>
		<input class="mx-1 h-10 text-blue-dark font-bold text-sm pl-4 w-auto w-1/8" type="text" placeholder="Opties" name="options" id="options" {% if craft.app.request.getParam('options') %} value="{{craft.app.request.getParam('options')}}" {% endif %}>
		<input class="ml-1 h-10 bg-blue-dark font-bold text-sm text-white w-1/8" value="Zoeken" type="submit">
</form>
```

and in my url i get the following:
![image](https://user-images.githubusercontent.com/9035369/47566704-cc0d1d00-d92c-11e8-957e-910219d8a57e.png)

Probably because it can't figure out the data from the twig calls? Because the value of my submit button gets transmitted correctly.

EDIT: seems like it's only the select that is not transmitting. Most likely a problem with my code. you can ignore this. :)

**Comment by gmrchk** [comment]
Hi @Geestig, just noticed your closed issue. 

You're correct, swup ignores `select` when sending with `get` method, and that's of course not a correct behavior. Forms are quite new to the swup so there might be some bugs I didn't think of. Good catch! I will fix that ASAP.

**Comment by gmrchk** [comment]
Swup now sends values of selects with `GET` method. Keep in mind that it's still only intended for simple forms so, for example, select with multiple values would still be a problem with `GET` method, although it would work just fine with `POST`.
