### ISSUE TITLE
Some pages stop on swup:pageRetrievedFromCache

### ISSUE THREAD

**Issue by 23d1** [gmrchk/swup#76]
Not sure what is causing this on some pages. Any ideas? I don't get any console errors, I can just see that the process stops at swup:pageRetrievedFromCache.

**Comment by gmrchk** [comment]
This most likely means that some of the elements selected by [animationSelector](https://github.com/gmrchk/swup#animation-selector) are not animating (don't have the required CSS for the hidden state defined), which means that swup waits for the animation to finish to replace the content, but animation never even starts.

**Comment by 23d1** [comment]
It's actually there, all pages follow the same template in the backend. I'm trying to figure out if it might be a tag that isn't closed, will report back. In the mean time—what else might it be?

**Comment by gmrchk** [comment]
I would say a promise of animation not resolving is the safest bet, all three `is-*` classes on `html` tag might also give you a hint of the same problem. Maybe some class of random element that has a `transition-` string in it by a coincidence, which gets selected by swup as well? 

A demo or code example would be awesome if the problem persists.

**Comment by 23d1** [comment]
Hmm. That might be the case. Would `[class*="a-"]` capture any case where there's an ...a-... somewhere in the string? Like `.fooa-bar`?

**Comment by gmrchk** [comment]
Yep

**Comment by 23d1** [comment]
Got it. I really should test before asking (sorry!). I changed to .transition-block and now it works wonderfully. Thanks for the fantastic responsiveness!
