### ISSUE TITLE
.on missing in minified distribution

### ISSUE THREAD

**Issue by maccyd10** [gmrchk/swup#79]
calling swup.on in minified version results in "Uncaught TypeError: swup.on is not a function"

**Comment by gmrchk** [comment]
Hi @maccyd10,

All seems to work for me in minified, non-minified, as well as "npm" version (lib folder) of swup. Are you sure you're on the latest version?

**Comment by studioSmacznego** [comment]
@maccyd10 @gmrchk 

I'm using swupjs.min.js and I found that if debugMode: true, then swup.on works fine. When debugMode: false, console says it is not a function. Switching from swup.on to document.addEventListener worked to fix this for me.

**Comment by benjspriggs** [comment]
+1 to this, seeing similar issues in the minified version 1.2.2.
