### ISSUE TITLE
swupGtmPlugin not working

### ISSUE THREAD

**Issue by DaveWoody** [gmrchk/swup#80]
Hey me again,
everything ( animation wise ) works great.
Still i got some problems getting gtag working properly on one of my clients sites. It does initiliaze gtag and google analytics is showing me the right realtime site i am looking at.

But as soon as i switch sites it keep showing me the first site i load the page the first time.

I tried the plugin. I also tried an add event listener. Still no luck.

What am i doing wrong?

[My clients site](https://www.trodatec.de)
[Link to my swup file](https://www.trodatec.de/wp-content/themes/trodatec/js/custom.js?ver=0.8.4.1542388890)

Appreciate all the help i can get. Thanks for your time!

**Comment by gmrchk** [comment]
Hi @DaveWoody,

If I understand correctly, when you navigate through the site with swup, real-time location in GA still shows the first page, right?

You can load GA with [Javascripts tracking snippet](https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet) and use [swupGaPlugin](https://github.com/gmrchk/swup#swupgaplugin), which should work fine. 

When loading GA different ways (like you do with gtag), it seems that the page view needs to be triggered in a different way (maybe like [this](https://developers.google.com/analytics/devguides/collection/gtagjs/pages), but I haven't tried that). I think I've seen one more approach somewhere on StackOverflow as well. 

If you actually want to use GTM with swupGtmPlugin as the title of the issue says, you need to associate triggered **VirtualPageview** event with *page view* in GTM.

**Comment by DaveWoody** [comment]
Working! 
I used Javascripts tracking snippet in combination with swupGaPlugin.

Thanks gmrchk!
