### ISSUE TITLE
Certain transition properties cause Swup to freeze

### ISSUE THREAD

**Issue by kybradeck** [gmrchk/swup#85]
Mostly loving Swup so far. It's definitely the simplest page transition library I've worked with, and it's something that's much needed! Thank you @gmrchk for all of your work. 😄 

I'm currently struggling with what seems like it should be a simple issue:

1. I want to fade out the `main` content between page changes. I've gotten this working successfully.
2. I want to preserve the `header` (outside of `main`) so that it stays fixed between page changes, but I'd like to smoothly animate the currently active menu item. (For example, by changing the color of the text and giving it an underline.) My templates add an `.active` class to the `<a>` representing the current area of the site.

The basic structure of my pages looks like this:
```html
<body>
  <header id="header" class="transition-header">
    <a>Page 1</a>
    <a class="active">Page 2</a>
    <a>Page 3</a>
  </header>
  <main id="swup" class="transition-fade">
    ...
  </main>
</body>
```

And I've configured Swup like this:
```js
document.addEventListener('DOMContentLoaded', function (event) {
  const swup = new Swup({
    elements: ['#swup', '#header']
  })
  ...
})
```

For the body, I have these styles. They work.
```scss
.transition-fade {
  transition: .2s;
  opacity: 1;
}

html.is-animating .transition-fade {
  opacity: 0;
}
```

When working with the CSS for the header, that's where I've started running into problems. Here's what I've discovered:

1. If I give the class `.transition-header` to `#header` but don't include matching CSS, Swup will freeze and refuse to load pages. (It fails silently and debugging shows it stuck at `pageRetrievedFromCache`.)

```scss
// Will cause Swup to freeze

// .transition-header {
// }

// html.is-animating .transition-header {
// }
```

2. If I try to style any elements using `.transition-header` as a parent class, Swup will freeze.

```scss
// Will cause Swup to freeze

.transition-header a.active {
  // Anything
}

html.is-animating .transition-header a.active {
  // Anything
}
```

3. If I omit a `transition` property, Swup will freeze.

```scss
// Will cause Swup to freeze

.transition-header {
  opacity: 1;
  // transition: .2s;
}

html.is-animating .transition-header {
  opacity: 0;
}
```

4. If I include a `transition` property but _don't_ include matching properties to transition between, Swup will freeze.

```scss
// Will cause Swup to freeze

.transition-header {
  // opacity: 1;
  transition: .2s;
}

html.is-animating .transition-header {
  // opacity: 0;
}
```

I'm not sure if I've set something up wrong, or my expectations of how Swup works are off. Would love to know what I'm doing wrong if that's the case!

If my expectations are correct, one class or one CSS property on one page being wrong causing pages to fail to load is... scary. And it makes me not want to use Swup on production sites, despite how amazing it's been for things like page caching and pre-rendering on hover.

If something causes Swup to fail, more helpful debug messages would go a long way toward educating new users like me about what's possible versus what isn't. Regardless of debugging messages, I think it'd be great to have the option to enable graceful fallbacks for when transitions fail.

**Comment by drivebass** [comment]
The .transition-class needs to have both a property and a transition duration for swup to wait for that element to animate. In all cases you describe you don't include either one or both of them. 
1. No .transition-header class in your css
2. This targets child elements inside .transition-class element but actually still there is no .transition-header class declared in your css.
3. The .transition-header class is missing duration.
4. The .transition-header class is missing property.

Have you tried the following:
`.transition-header {
  opacity: 1;
  transition: .2s;
}

html.is-animating .transition-header {
  opacity: 0;
}`

However, from what you describe if I understand correctly, you want the #header to stay fixed and visible and just animate the a.active class at the respective page. If that's the case you don't need any .transition-class for the header at all. You just need to add transitions to the .active class for the properties you'd like. With this when #header content is replaced by swup the current active menu item will animate.  

`#header a{
    text-decoration: none;
    color: black;
    transition: color 0.3s ease;
}
#header a.active{
    text-decoration: underline;
    color: red;
}
`

**Comment by gmrchk** [comment]
As @drivebass mentioned, the styles definitions are not correct. You need some `is-animating` styles defined for all `transition-*` elements, as swup will wait for them to finish the animation, even if there is none. 

If the only thing you want to do is change the active class, you can do that without swup at all (not replace header by swup), as your header stays on the page. The example below would just remove all the `active` classes and add the `active` class to the clicked element. 

```javascript
var headerLinks = Array.prototype.slice.call(document.querySelectorAll('#header a'));

headerLinks.forEach(function(clickedItem) {
    // create click listener for all links
    clickedItem.addEventListener(function(event) {
          headerLinks.forEach(function(item) {
              item.classList.remove('active');
          });
          clickedItem.classList.add('active');
    }); 
});
```

This way you can manipulate the header however you like, add classes, remove classes and just whatever really. It's really flexible and I would probably go this way.

Another option is to remove the active styles from the links when the page is in the process of transition. 

```css
#header a {
    color: blue;
}

#header a.active{
    color: red;
}

html.is-animating #header a.active{
    color: blue;
}
```

This way the active styles are removed by `is-animating` class, so by the time swup is replacing the content of header, none of the links look active and there is no blink. This approach is used [here](https://plzen.cz.panasonic.com/) as well. Note that there is no `transition-*` class involved here, so swup doesn't wait for the links to finish the animation. That's not necessarily a bad thing, swup doesn't have to wait for X elements to finish the animation. As long as the timing is reasonable an somewhat similar, all you need is one element that would control the timing for swup. That also solves the problem of making a mistake somewhere in your code and getting swup stuck by mistake somewhere on your website. 

To answer the question about not throwing some kind of reasonable error when this kind of stuff happens... There are certain situations that don't throw an error and get swup stuck at some point of the lifecycle, as you already found out. This is mostly a problem for beginners or people using swup for the first time. A similar issue is related to using links with `href="about.html"`. Those links are not handled by swup by default, and so, the page will just navigate to the other page without any animation. It's kind of a problematic to detect this kind of error, as swup would have to save stuff to localStorage(?) about the manual navigation between pages and would have to include long descriptive errors of what is happening, and so, bloating the code. I've been thinking some time about creating a plugin that would serve only for development purposes and would detect and display explanations of those problematic errors. If you have any ideas/suggestions for that, I would be more than happy to hear it!

**Comment by kybradeck** [comment]
Thank you both for your detailed responses! That helps a lot. 😄

Not over-investing in error messaging makes sense, especially since it's not something we'd want bloating production code. A separate package for detailed debugging would be superb, but also sounds like a lot of work, as you mentioned. A good short-term solution could be to update the readme with explicit notes about what properties swup looks for, common formatting errors that can cause it to fail, and how to resolve them.

For example, this:

> You need some is-animating styles defined for all transition-* elements, as swup will wait for them to finish the animation, even if there is none.

is not something that I understood intuitively, but now that I know, it'll be easy to fix if that happens again.

After playing around last night I discovered that Swup basically does as-wanted without a transition class at all, so that's the solution I'm going with at the moment. :) No extra JS needed.

**Comment by gmrchk** [comment]
Glad you solved your issue. 

I see, so you're going for simply enhancing load speed using swup... I have done it several times but didn't know people do the same as well. I see it as kind of a nice "accidental" feature.

I will extend the docs with some Common Issues section and include an explanation for issues like yours in there. 

Thanks for your input guys @kybradeck @drivebass
