### ISSUE TITLE
different scripts on each page

### ISSUE THREAD

**Issue by MartDSam** [gmrchk/swup#86]
Firstly I want to congratulate for working with SWUP, it's a very good library.

I was able to do everything I wanted, but I'm doubtful in just one point.

1 - I have the HOME page and I have the CONTACT page.

2 - On the HOME page I have in the footer the following scripts:
- swup
- main
- gsap

3 - In the CONTACT page I have in the footer the following scripts:
- swup
- main
- ScrollMagic

4 - When I change pages have some way to remove the scripts that I will not use and load new libraries of scripts that are in the new page?

5 - I do not want to by the scripts in HEAD, because it is a bad practice.

Thank you!

**Comment by 23d1** [comment]
I would just check for the class on that page. For example, if the `<body>` tag has the `.contact-page` class, I would den in the function to run the scripts on all pageviews do something like;

```
swup
main
if (document.querySelector('body.contact-page') {
        ScrollMagic
}
```

**Comment by MartDSam** [comment]
But for this the scrollMagic library should already be loaded right?

I saw in some discussion the suggestion that all site libraries should be loaded together. But that ends up affecting a lot in the first byte of the site.

I wanted to load some libraries as scrollMagic, only on specific pages.

Thanks :D

**Comment by gmrchk** [comment]
Hi and thanks @MartDSam 

Yes, that means the library needs to be loaded, no matter what page are you accessing on the first load. 

Another option is to use bundler (like webpack) and code splitting to separate your code into chunks that get loaded when the library is needed. Of course, that's a whole another story that you should investigate in case you want to do this, but [Gia](https://github.com/giantcz/gia) might give you a head start as it doesn't require any additional setup for webpack to give you the code splitting abilities. Also, there is already a [demo](https://gmrchk.github.io/swup-gia-demo/index.html) ready using both Gia and swup together.

**Comment by MartDSam** [comment]
@gmrchk Thanks for your attention.

I understand. I'll try to use Gia, but I do not know how it works with wordpress. I still do not understand how it works, I will test in practice to see if I understand better hahaha

**Comment by gmrchk** [comment]
Alright! It would probably also help to read some more about webpack, code splitting and all that stuff around it if you haven't already.

I think we figured out what you need to do or how you could fix your problem. Closing for now.
