### ISSUE TITLE
"Promise not supported"

### ISSUE THREAD

**Issue by esseifforte** [gmrchk/swup#88]
Hi,
thank you for this Js script! I'm testing it and after configuration, in all my browsers,
appears "Promise not supported" warning.

thank you in advance

**Comment by gmrchk** [comment]
Hi,

This most likely means that you are including some kind of polyfill for Promises in your code, which overwrites native browser one. Swup checks for support of `pushState`, `transitionEnd` event and native Promise.

`pushState` and `transitionEnd` is quite widely supported nowadays, so if you don't mean to support IE 9 or lower, you can bypass the support check with options.

```javascript
var swup = new Swup({
    support: false,
});
```

However, I don't think a Promise polyfill should overwrite a native Promise implemented in a browser (if there is one), so you might consider using another polyfill.

**Comment by esseifforte** [comment]
wow! thanks for the quick response! basically I created a plugin.js file with some plugins, and the error was there, not in the main.js.
now, with that string you gave me the error is gone! thank you.


ps. do I have to include both swup.js and swupjs.js or just to create js animations just swupjs.js?

**Comment by gmrchk** [comment]
swupjs already includes and extends swup. No need to include both.

Cheers
