### ISSUE TITLE
Swup form submit error in IE11 -  Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by marie-maxime** [gmrchk/swup#93]
When trying to submit a form with `data-swup-form` in IE11, I get this error: 
`Object doesn't support property or method 'forEach'`

I think this is because of a `forEach` used directly on a NodeList here:
https://github.com/gmrchk/swup/blob/master/src/index.js#L403

**Comment by sw-double** [comment]
You should just add [polyfill](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Polyfill) before using swup

**Comment by gmrchk** [comment]
I think this is something that should be handled by swup correctly. I have fixed this for all occurrences in swup some time ago... Guess I have somehow missed this one. 

Thanks for reporting. Fixed in the new version.
