### ISSUE TITLE
Using redirect from JS without swup reloading

### ISSUE THREAD

**Issue by coorum** [gmrchk/swup#96]
Hi, 
I've met with a problem when I'm trying to change href with `window.location.href` from JS, I need to reload the swup again
Maybe there is an option how to redirect straightly from swup? Or without reloading it again?

~~P.S. I thought about hiding `<a>` tag with `position: absolute` and `display: none` and when I need to trigger `click` from jQuery, what do you think about it?~~

**Update**
I've discovered that `$(selector).trigger("click")` or `DOMSelector.click()` are not working

**Comment by gmrchk** [comment]
Setting the `window.location.href` will simply redirect the page to the defined URL, which is probably not what you want. You could update the URL with [pushState](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method) or [replaceState](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method) (those do not change the content of the page, only the address in URL bar) depending on what you need, but keep in mind that swup "marks" the changes it makes to the browser history and won't act on popstates (back/forward buttons) if it was created by other source.

If your goal is to transition to the required page as it would utilising swup after the click of the link, use swups loadPage method described in the [API](https://github.com/gmrchk/swup#api) section.

**Comment by coorum** [comment]
@gmrchk thanks a lot!
Didn't play with swup API on 100% and missed some moment with `loadPage`
Thanks for your help
