### ISSUE TITLE
Reloading reCaptcha script

### ISSUE THREAD

**Issue by CasonWebDev** [gmrchk/swup#98]
Hello, my website using swup, have a contact form each page, and i want to use reCaptcha in then, but, on change the page the reCaptcha script has not reloaded, and this script is only a import of a .js file in the head of site..
any ideia how i solve this?
thanks.

**Comment by CasonWebDev** [comment]
I fixed the issue...
solution calling this method:

```
grecaptcha.render("recaptcha", {
        sitekey: 'SITE_KEY',
        callback: 'onSubmit',
        size: 'invisible'
 });
```

**Comment by gmrchk** [comment]
Was just about to answer... this could be also helpful:

Reloading on the `contentReplaced` event as stated [here](https://stackoverflow.com/a/3457203/5831449). 

```javascript
var swup = new Swup();
swup.on('contentReplaced', function () {
    grecaptcha.reset();
});
```
or
```javascript
document.addEventListener('swup:contentReplaced', function () {
    grecaptcha.reset();
});
```

**Comment by byebyers** [comment]
Regarding this
```
swup.on('contentReplaced', function () {
    grecaptcha.reset();
});
```
Can this be triggered on a specific page? I am able to get my ReCaptcha work on the first load but now get recaptcha errors when I move to other pages.

**Comment by byebyers** [comment]
I figured this out by checking the length of the id. Easy stuff.

**Comment by MikeHarrison** [comment]
Hi,
I am having the same issue. I have the recaptcha script in the header (`<script src="https://www.google.com/recaptcha/api.js" defer></script>`), and the captcha appears and works if I load the page as normal. If I arrive to the page via Swup then the captcha does not appear.

I have tried this in the my js: 
```
document.addEventListener('swup:contentReplaced', function(){
  grecaptcha.reset();
});
```
But this gives me the following console error: `Error: No reCAPTCHA clients exist.` when I arrive at the page via Swup. This error is also appearing on other pages where there is not a form (but I guess I would expect that). If anyone has any pointers that would be great.

**Comment by byebyers** [comment]
This is what I did with my file in case this helps you. 

`let options = {
  animateScroll: false
};
const swup = new Swup(options);
swup.on('contentReplaced', function () {
  if ($("#re-captcha").length > 0) {
      onloadCallback();
  }
});`

Basically I checked the page for a recaptcha id. Also I had to use V2 recaptcha for my site instead of V3. Hope this helps.

**Comment by gmrchk** [comment]
Hi @CasonWebDev, and anyone in this thread. Did anyone here make it work properly with a reCaptcha v3? I would like to make a swup plugin to get rid of this issue once and for all. 

If anyone here would like to take care of it - awesome! If not, I will happily do it myself... just asking for directions before digging into it on my own, as I haven't used reCaptcha anywhere for ages.

**Comment by MikeHarrison** [comment]
Just V2 here - I did get it working in the end with this in my js file:

```
document.addEventListener('swup:contentReplaced', function(){

  var forms = document.querySelectorAll('*[id^="form"]');

  if(forms.length > 0) {
    grecaptcha.render("recaptcha", {
        'sitekey': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    });
  }

});
```

**Comment by byebyers** [comment]
@gmrchk I was not able to and had to use v2. Would love to see this implemented though. I could join and help when I get back from vacation on July 23rd.

**Comment by gmrchk** [comment]
I have created a repo for the plugin. I won't get to it this week at least, so if anyone wants to dig into it, please, create a PR.

**Comment by bknightly** [comment]
> I have created a [repo](https://github.com/swup/recaptcha-plugin) for the plugin. I won't get to it this week at least, so if anyone wants to dig into it, please, create a PR.

Any timeline for when said plugin will be ready for use?

**Comment by DESIGNfromWITHIN** [comment]
Is there still no solution for SWUP and Google Recaptcha V3? I really need it.

**Comment by daun** [comment]
There's currently no official recaptcha plugin. None of the current maintainers have had a need to integrate this into their projects and thus wouldn't be the most reliable judges on whether the plugin is working as expected.

Feel free to give it a stab yourself, though! [Searching for `swup` + `recaptcha` on GitHub](https://github.com/search?type=code&auto_enroll=true&q=swup+recaptcha) should give you some pointers and example projects that have integrated both already, without necessarily open-sourcing their code as a re-usable plugin.

**Comment by daun** [comment]
Theoretically, the way to go here would be to hook right after `page:view` to trigger any Recaptcha code. That part's easy. The difficult part is setting up your own backend server to deal with verification requests and sending those requests to your backend.

```html
<script src="https://www.google.com/recaptcha/api.js?render=RECAPTCHA-SITE-KEY"></script>
```

```js
swup.hooks.on('page:view', () => {
  grecaptcha.ready(() => {
    grecaptcha.execute('RECAPTCHA-SITE-KEY', { action: 'pageview' }).then((token) => {
      fetch('/backend/recaptcha/verify', { method: 'POST', body: JSON.stringify({ token }) });
    });
  });
});
```

**Comment by DESIGNfromWITHIN** [comment]
Wow never realised that this was so difficult...
Will maybe try. Without recaptcha..

Op vr 17 nov. 2023 18:00 schreef Philipp Daun ***@***.***>:

**Comment by MikeHarrison** [comment]
Maybe not helpful, but depending on your site, recently I have been using server-side validation using a honeypot field combined with a honeytime setup as well. This seems pretty effective at stopping spam. This combined with Swup's inline forms handling - https://swup.js.org/plugins/forms-plugin/#inline-forms - to flash back any issues, ends up in a pretty nice system. Also no need to click on various pictures of bicycles 🚲

**Comment by daun** [comment]
Agree with @MikeHarrison here — honeypot fields are surprisingly effective and non-intrusive for users. If you're still getting lots of spam even when using a honeypot field, you could set the `form[action]` attribute dynamically via JS on the frontend. That combination is usually enough for all spam. Only after that does recaptcha make sense if terms of complexity.

**Comment by hirasso** [comment]
@MikeHarrison would you like to expand on what exactly you mean with `honeytime`? Something like a check if the form was submitted too fast? Sounds interesting :)

**Comment by MikeHarrison** [comment]
Hi - yes that's basically it. Bots usually fill in forms way faster than a human, so it measures time on the page, and if that is below a certain threshold the form won't submit.

I use a CMS called Kirby for my builds, which has a forms plugin that does all the heavy lifting for you. This is a bit of detail about how it works:

[https://kirby-uniform.readthedocs.io/en/latest/guards/honeytime/](https://kirby-uniform.readthedocs.io/en/latest/guards/honeytime/)

Running that as well as a honeypot field has cut out bot spam on my sites, while not putting any additional burden on the user.

**Comment by hirasso** [comment]
Interesting, thanks for sharing! This will only work if the form is not being served from a static cache, if I'm not mistaken? But still, like the concept! Kirby is a great tool, have also used it before.
