### ISSUE TITLE
How to load page with html?

### ISSUE THREAD

**Issue by barisyild** [gmrchk/swup#99]
How to load page with html?

**Comment by alcantara** [comment]
Is swup able to work with static websites? For example Jekyll and github pages?

**Comment by alcantara** [comment]
> Can you explain the question further?

Not op. Does swup and gia work with static websites? For example Jekyll and github pages?

**Comment by gmrchk** [comment]
@alcantara if you have a question, please, open an issue so we don't mix multiple topics together.
